// scoreplace.app — Release notes (lazy-loaded)
// Loaded on demand when the user opens "Notas de versões" in help modal.
//
// Convenção de versão (a partir de 30 Abr 2026): MAJOR.MINOR.PATCH-channel.
//
// ⚠️ NOTAS RESUMIDAS POR VERSÃO NATIVA (a partir de jul/2026, pedido do dono):
// as notas mostradas ao usuário são CONSOLIDADAS no nível da versão nativa/loja
// (MINOR — 1.0, 1.1, 1.2, 1.3…) — UMA nota-resumo por minor, com os destaques
// agrupados por tema. NÃO ter mais nota detalhada por patch (1.x.y). Cada patch
// bumpado no dia continua no changelog técnico (git/commits); aqui o usuário vê o
// resumo da versão que foi/vai pra loja. Ao promover um novo minor, dobrar os
// destaques dos patches daquele ciclo num único bloco.
//
// Histórico completo da fase alpha → beta exportado pra
// docs/scoreplace_relatorio_alpha_to_beta.docx (registro local do dono).
// Histórico completo da fase beta → 1.0 (385 notas, 29 Abr → 13 Jul 2026)
// exportado pra docs/scoreplace_relatorio_beta_to_1.0.docx — a partir da v1.0
// o app mostra só as notas de 1.0 em diante.

window._RELEASE_NOTES_HTML = (function () {
  var html =
    // ── v1.8 ─────────────────────────────────────────────────────────────────
    '<div style="margin-bottom:1rem;border:2px solid #a78bfa;border-radius:12px;padding:14px 16px;background:rgba(167,139,250,0.08);">' +
      '<div style="font-weight:800; color:#c4b5fd; font-size:1rem; margin-bottom:8px;">\uD83C\uDFC5 v1.8 \u2014 Sua coloca\u00e7\u00e3o calculada, conta duplicada que o app pergunta antes, e o app s\u00f3 abre quando terminou de carregar <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Agosto, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>\ud83e\ude79 Corre\u00e7\u00e3o: app abrindo travado no celular:</b> em alguns casos o app abria mostrando s\u00f3 o topo e o resto da p\u00e1gina n\u00e3o aparecia nem rolava. A trava de rolagem usada pelos pop-ups ficava presa quando o navegador segurava um quadro de anima\u00e7\u00e3o (ao voltar de outro app, por exemplo). Agora ela se destrava sozinha.</li>' +
        '<li><b>\ud83d\udcf1 No celular o app diz por que a leitura do letzplay n\u00e3o roda ali:</b> tocar em \u201cPuxar hist\u00f3rico completo\u201d abre um aviso explicando que a leitura \u00e9 feita por uma extens\u00e3o do Chrome, que s\u00f3 existe no computador. Antes o bot\u00e3o simplesmente n\u00e3o fazia nada. E a categoria oficial parou de exibir o nome do torneio junto (\u201c11\u00ba BT House Open - MASCULINA C\u201d virou \u201cMASCULINA C\u201d).</li>' +
        '<li><b>\ud83e\uddf9 Nome de torneio repetido, e a leitura mais silenciosa:</b> alguns torneios do letzplay chegavam com o nome escrito duas vezes ("TORNEIO RP 2026 - 10 anos - TORNEIO RP 2026 - 10 anos") \u2014 agora aparecem uma vez s\u00f3, inclusive nas leituras j\u00e1 feitas. E a barra de progresso parou de exibir avisos t\u00e9cnicos sobre a leitura: ela mostra o passo em curso e o tempo decorrido, e mais nada.</li>' +
        '<li><b>\ud83e\udde9 Extens\u00e3o nova: o app manda pro caminho que funciona:</b> quando sai uma vers\u00e3o nova da extens\u00e3o do letzplay, a Chrome Web Store leva alguns dias revisando. Nesse intervalo o app parava de importar e mandava voc\u00ea pra loja \u2014 que ainda tinha a vers\u00e3o antiga, e o Chrome respondia \u201cj\u00e1 est\u00e1 atualizada\u201d. Agora, enquanto a revis\u00e3o n\u00e3o sai, ele oferece o download direto \u2014 sem tirar a loja da tela, que continua ali como o destino permanente. Quando a vers\u00e3o sair por l\u00e1, o download some sozinho e o Chrome volta a atualizar tudo automaticamente.</li>' +
        '<li><b>\ud83c\udfc5 At\u00e9 onde voc\u00ea chegou no torneio \u2014 e com quem:</b> a ficha do atleta passa a dizer a <b>coloca\u00e7\u00e3o entre TODOS os participantes</b>, n\u00e3o a posi\u00e7\u00e3o dentro do grupo: Campe\u00e3o, Vice, 3\u00ba/4\u00ba na semifinal, 5\u00ba/7\u00ba nas quartas \u2014 sempre com a fase entre par\u00eanteses e o nome da sua dupla ao lado. Posi\u00e7\u00e3o dentro do grupo ("GRUPO 03 \u00b7 2\u00ba de 3") deixou de aparecer: ela n\u00e3o diz nada sobre o torneio. Quando n\u00e3o d\u00e1 pra apurar a coloca\u00e7\u00e3o geral, a linha fica sem coloca\u00e7\u00e3o \u2014 em ranking, a posi\u00e7\u00e3o continua saindo normalmente, porque ali ela j\u00e1 \u00e9 a classifica\u00e7\u00e3o inteira.</li>' +
        '<li><b>\ud83c\udfbd Sua categoria \u00e9 Masculina ou Feminina \u2014 nunca \u201cMista\u201d:</b> \u201cMista\u201d \u00e9 a categoria do torneio, n\u00e3o do atleta. Quem jogou uma mista aparecia com ela como categoria oficial; agora vale a faixa disputada no pr\u00f3prio g\u00eanero, e quando s\u00f3 existe torneio misto o app mostra apenas o n\u00edvel (D, C+\u2026) em vez de afirmar um g\u00eanero que o dado n\u00e3o diz.</li>' +
        '<li><b>\ud83d\udd22 Seus pontos em destaque:</b> o n\u00famero que resume seu n\u00edvel saiu da letra mi\u00fada ao lado da forma e ganhou um canto pr\u00f3prio, em corpo grande.</li>' +
        '<li><b>\uD83E\uDDE9 A extens\u00e3o do letzplay est\u00e1 na Chrome Web Store:</b> instalar virou <b>um clique</b> e a atualiza\u00e7\u00e3o passou a ser <b>autom\u00e1tica</b> \u2014 acabou o vaiv\u00e9m de baixar zip e reinstalar na m\u00e3o a cada vers\u00e3o. O zip continua existindo como alternativa enquanto a loja revisa uma vers\u00e3o nova.</li>' +
        '<li><b>\uD83D\uDC65 Conta duplicada: o app pergunta antes:</b> se voc\u00ea j\u00e1 tem outra conta aqui, agora ele <b>reconhece o seu nome escrito de outro jeito</b> \u2014 com ponto, sem acento, com a inicial abreviada ou faltando uma letra \u2014 e <b>pergunta antes</b> de deixar voc\u00ea se inscrever duas vezes no mesmo torneio. Se o <b>celular ou o e-mail j\u00e1 autenticado</b> for o mesmo nos dois lados, a\u00ed ele <b>une na hora</b> \u2014 \u00e9 prova de que a conta \u00e9 sua. Fora isso <b>nada \u00e9 unido sozinho</b>: s\u00f3 depois que voc\u00ea confirmar a posse da outra conta, pelo e-mail ou pelo celular dela. E se voc\u00ea disser que n\u00e3o \u00e9 voc\u00ea, ele <b>n\u00e3o pergunta de novo</b> \u2014 s\u00f3 volta a perguntar se aparecer algo mais forte, como o mesmo celular.</li>' +
        '<li><b>\u23F3 O app s\u00f3 abre quando terminou de carregar:</b> antes a tela era liberada <b>por tempo</b>, mesmo com os dados ainda a caminho \u2014 voc\u00ea entrava, ia direto procurar o torneio e a interface <b>travava por alguns segundos</b>. Agora quem libera \u00e9 o <b>dado</b>: a tela inicial aparece quando a dashboard est\u00e1 realmente pronta, e a navega\u00e7\u00e3o j\u00e1 come\u00e7a fluida.</li>' +
        '<li><b>\uD83D\uDD0E Busca da chave que acha quem est\u00e1 fora:</b> procurar um nome agora encontra tamb\u00e9m quem est\u00e1 em <b>Desativados</b>, <b>Lista de espera</b> e <b>W.O.</b>, e esconde as caixas que ficaram sem ningu\u00e9m. O <b>cabe\u00e7alho parou de deslizar</b> ao limpar o campo no \u2715, e os cart\u00f5es da <b>Organiza\u00e7\u00e3o</b> passaram a respeitar o filtro \u2014 quem n\u00e3o bate com a busca some junto.</li>' +
        '<li><b>\uD83D\uDCE8 O convite deixou de nascer escondido:</b> ao abrir <b>Convidar</b> num torneio, a primeira linha do painel ficava <b>atr\u00e1s da barra de busca</b>. Agora ele abre logo abaixo do cabe\u00e7alho, inteiro, e rola dentro de si em telas menores.</li>' +
        '<li><b>\uD83D\uDC64 Quem se inscreveu n\u00e3o some mais:</b> se a internet caísse no meio da inscri\u00e7\u00e3o \u2014 4G ruim na quadra, aba fechada \u2014 a tela dizia <b>inscrito</b> e o servidor nunca recebia. A pessoa ficava num limbo: aparecia no elenco, mas <b>fora de qualquer grupo</b> e invis\u00edvel na rodada. Agora a inscri\u00e7\u00e3o s\u00f3 \u00e9 dada como feita quando o <b>servidor confirma</b>, e o app avisa se n\u00e3o conseguiu. Junto disso, um <b>grupo j\u00e1 formado n\u00e3o pode mais desaparecer</b> por um aparelho que estava com a tela aberta h\u00e1 muito tempo.</li>' +
        '<li><b>\uD83D\uDCCD \u201cPlace\u201d virou \u201cPresen\u00e7a\u201d:</b> o bot\u00e3o mudou de nome pra dizer o que ele faz de verdade \u2014 marcar que voc\u00ea est\u00e1 no local. Mesma tela, mesmo lugar.</li>' +
        '<li><b>\uD83E\uDDF9 Verifica\u00e7\u00e3o do letzplay mais honesta:</b> uma leitura s\u00f3 conta como <b>verificada</b> (nome verde) quando foi feita pela <b>vers\u00e3o atual</b> da extens\u00e3o. Leituras antigas voltam a aparecer como <b>autorizadas mas ainda n\u00e3o conferidas</b> at\u00e9 serem puxadas de novo \u2014 antes elas eram tratadas como conferidas mesmo tendo vindo de um motor que j\u00e1 se sabia defeituoso.</li>' +
      '</ul>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #22d3ee;border-radius:12px;padding:14px 16px;background:rgba(34,211,238,0.08);">' +
      '<div style="font-weight:800; color:#67e8f9; font-size:1rem; margin-bottom:8px;">🛡️ v1.7 — Sorteio que não se apaga, contato direto com quem joga com você, e placar validado no servidor <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Agosto, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>🛟 Nada do que já aconteceu se perde:</b> quando duas pessoas mexem no mesmo torneio ao mesmo tempo, o aparelho que estava com a tela aberta há mais tempo podia gravar por cima e <b>apagar o que aconteceu no meio tempo</b>. Agora não apaga mais: <b>inscrição</b>, <b>placar já lançado</b>, <b>rodada recém-sorteada</b>, <b>jogo de quem entrou depois</b>, <b>link do grupo de WhatsApp</b>, <b>horário combinado</b>, <b>substituição por W.O.</b> e <b>aceite de co-organização</b> ficam de pé. O que você quis mudar continua sendo salvo normalmente — só o que ficou para trás é que volta.</li>' +
        '<li><b>🔒 Sorteio realizado não se apaga:</b> depois de sorteado, o chaveamento <b>não é mais destruído</b> para fazer outro — nem por engano, nem com resultados já lançados. Na fase eliminatória a chave é uma árvore fechada e o app recusa; em fase de rodadas, o que existe é <b>gerar uma rodada extra</b>, que acrescenta sem apagar nada do que já foi jogado.</li>' +
        '<li><b>💬 Falar com quem joga com você:</b> na classificação, um botão verde ao lado do nome abre o <b>WhatsApp direto</b> com a pessoa — ou o e-mail, quando ela não tem telefone cadastrado. Todo mundo do seu grupo pode falar com o grupo; o organizador fala com qualquer inscrito, em qualquer classificação.</li>' +
        '<li><b>👤 Ficha do jogador na classificação:</b> tocar no nome na tabela abre a <b>ficha completa</b> — foto, histórico e troféus —, a mesma da Análise de Inscritos. Nos cards da chave o nome deixou de abrir ficha: na quadra, o card é área de toque para lançar placar.</li>' +
        '<li><b>🛡️ Placar validado no servidor:</b> quem pode lançar o resultado de cada jogo passou a ser decidido <b>no servidor</b>, e não só no aparelho — quem está naquele jogo, o que a fase permite, e em que ponto está a negociação entre os times. Na prática você não vê diferença; o que muda é que a regra passa a valer igual para todo mundo.</li>' +
        '<li><b>🚫 W.O. agora é sempre a mesma coisa:</b> quem leva W.O. fica com <b>0 pontos na rodada</b> e vai para os <b>Desativados</b> — não vai mais para a lista de espera. A fila passou a depender de um ato da própria pessoa: quando ela liga o botão <b>Ativado</b> no torneio, entra no <b>fim da lista de espera</b> e volta a jogar quando chegar a vez. O organizador não escolhe mais o destino, e o primeiro da fila continua assumindo a vaga até o fim do torneio.</li>' +
        '<li><b>🔁 O botão “Ativado” não volta mais sozinho:</b> quem estava desativado e ligava o botão via ele <b>voltar para “Desativado”</b> segundos depois, por mais que tentasse. A ativação chegava a ser gravada, mas uma proteção do app — a que impede alguém de sumir do torneio por engano — entendia a ida para a <b>lista de espera</b> como se a pessoa tivesse sido apagada, e desfazia tudo. Agora ir para a fila é reconhecido como o que é: uma <b>mudança de lugar</b>, não um sumiço. E o botão passou a mostrar o seu estado de verdade: estando na fila e disponível, ele fica <b>Ativado</b> — antes dizia “Desativado” mesmo depois de você ligar. Junto disso, <b>reativar tira você da folga</b>: quem estava desativado e voltou passa a aparecer na <b>lista de espera</b>, e não mais entre os <b>Desativados</b> da rodada — inclusive quem já tinha reativado antes desta correção.</li>' +
        '<li><b>⏳ Quem se inscreveu depois do sorteio aparece:</b> a Análise de Inscritos agora mostra também a <b>lista de espera</b>, marcada como tal, para o organizador atribuir gênero e categoria antes de a pessoa entrar. E atribuir gênero <b>fixa de primeira</b> — antes era preciso repetir o processo.</li>' +
        '<li><b>⚖️ Proporção de homens e mulheres no sorteio:</b> em torneios <b>sem categoria por gênero</b> (todo mundo misturado), o organizador escolhe a proporção de cada 4 pessoas sorteadas — <b>50/50</b>, <b>25/75</b> ou <b>75/25</b> — na tela do sorteio equilibrado e também no criar/editar, dentro da fase. Com <b>Travar proporção</b> ligado, um grupo só se forma se a proporção for atendida <b>exatamente</b>, e quem não couber espera; desligado, o sorteio persegue a proporção e, quando não houver mais como mantê-la, <b>flexibiliza para incluir o máximo de gente</b>. Quem está sem gênero declarado <b>nunca é presumido</b> homem ou mulher — e o próprio sorteio deixa você preencher isso ali na hora. Com categorias separadas (Fem, Masc ou Misto) nada disso aparece: ali o sorteio já roda por categoria, e o Misto já é 50/50 por ser sorteio de duplas.</li>' +
        '<li><b>🛡️ Grupo fora da regra não nasce:</b> a composição de cada grupo passou a ser <b>conferida antes de o grupo existir</b>, e não depois. Um grupo que não atenda à proporção travada é recusado na porta em vez de aparecer montado para alguém perceber o erro depois.</li>' +
        '<li><b>🪪 Duas contas da mesma pessoa: o app pergunta antes de virar problema:</b> quando alguém se inscreve com uma conta nova e os sinais indicam que já está naquele torneio por outra (<b>mesmo celular</b> ou <b>mesmo nome</b>), o app avisa que <b>parece</b> ser a mesma pessoa e mostra <b>com qual conta</b> — com e-mail e telefone mascarados —, oferecendo unir as duas ali mesmo. Se não for você, basta dizer: o app <b>não volta a perguntar</b>. Organizador inscrevendo terceiro nunca passa por essa porta.</li>' +
        '<li><b>🔗 Unir contas não perde nada:</b> ao juntar duas contas suas, viajam junto <b>torneios, jogos, presenças, avisos, a leitura do letzplay e os dados do perfil</b> — e os dois logins continuam entrando. Vence a conta <b>mais ativa</b>, que absorve o que só existia na outra.</li>' +
        '<li><b>🏷️ Trocou o nome? Aparece igual em todo lugar:</b> classificação, cards da chave e a <b>busca</b> passaram a mostrar o nome do <b>perfil de agora</b>, e não o que ficou gravado no dia do sorteio. Antes a mesma pessoa podia aparecer com dois nomes em telas diferentes, e procurar pelo nome novo não achava os jogos dela.</li>' +
        '<li><b>🎯 Análise de Inscritos: a mudança vai para a pessoa certa:</b> mexer na categoria ou no gênero de <b>várias pessoas de uma vez</b> agora salva todas — e nunca mais grava no inscrito errado da lista. E ao salvar, os <b>dois botões</b> mostram “Salvando…” até terminar, para você não sair achando que já gravou.</li>' +
        '<li><b>🎾 Placar ao vivo redesenhado:</b> cada dupla virou uma <b>caixa colorida</b> com os nomes, o games/sets e o ponto dentro, e <b>quem saca fica em cima</b> (à esquerda, no celular deitado). Os números cresceram para ocupar a placa inteira, o <b>Desfazer atravessa a base</b> e nada mais encosta nas bordas — feito para ler de longe, com o celular apoiado na quadra.</li>' +
        '<li><b>📐 A tela inteira passou a ser usada:</b> no celular havia uma <b>faixa morta</b> no topo do placar e a placa do ponto <b>cobria o Desfazer</b> — dependendo do aparelho, o botão ficava debaixo do número. Os dois sumiram, no iPhone e no Android.</li>' +
        '<li><b>🏐 “Quem saca primeiro?” cabe numa tela só:</b> os quatro jogadores agora aparecem em <b>duas colunas</b> (seu time à esquerda, o adversário à direita), sem rolar para achar o quarto. O título e o Iniciar foram para o cabeçalho, e o botão Fechar repetido saiu.</li>' +
        '<li><b>⚡ Partida casual: menos rolagem para começar:</b> a modalidade ficou em <b>uma linha só</b> e os botões <b>Sortear Duplas</b> e <b>Rei/Rainha</b> agora ficam <b>lado a lado</b> — sobra tela para os jogadores e para o QR code de convite.</li>' +
        '<li><b>⌚ Relógio: o sacador é o mesmo dos dois lados:</b> ao escolher quem saca <b>no celular</b>, o relógio acende <b>o mesmo nome</b> na hora — antes cada um mostrava um, e dava para começar a partida com sacadores diferentes. E o <b>Encerrar do relógio agora encerra de verdade</b>: fecha o placar no celular, devolve você à tela de configuração e o relógio volta para a espera, em vez de ficar preso na tela do último resultado.</li>' +
        '<li><b>🎾 letzplay: o amistoso conta como jogo:</b> partidas <b>avulsas</b> (sem competição) passaram a entrar na sua leitura como jogo. Antes elas eram descartadas, e a barra ficava eternamente devendo — dizia “concluí” com a conta aberta, e o seu nome não fechava em verde na Análise.</li>' +
        '<li><b>⚖️ Empate em 5-5: você escolhe:</b> ao empatar o set (5-5, 6-6, 7-7…), o app pergunta em tela cheia se quer <b>prorrogar</b> (jogar até 2 games de vantagem) ou <b>ativar o tie-break</b> — números e botões grandes, pra decidir de longe, na quadra. Em partida casual ele pergunta <b>sempre</b>; em torneio vale a regra do organizador.</li>' +
        '<li><b>🎾 No tie-break o sacador continua do mesmo lado:</b> quem saca fica <b>sempre à esquerda</b> (deitado) ou <b>em cima</b> (em pé). Antes o lado congelava justamente no tie-break, que é onde o saque mais troca. Vale igual no relógio.</li>' +
        '<li><b>⌚ O relógio não trava mais ao encerrar:</b> ao tocar em Encerrar no fim da partida, o relógio ficava preso no placar final sem fazer mais nada. Agora ele volta pra uma tela própria.</li>' +
        '<li><b>🙋 Só o primeiro nome no placar:</b> a tela mostra <b>Rodrigo</b>, não <b>Rodrigo Barth</b> — sobra espaço e a fonte cresce. O sobrenome só aparece quando dois jogadores têm o mesmo primeiro nome, e só o quanto basta pra diferenciar.</li>' +
        '<li><b>📏 Placar maior na mesma tela:</b> havia espaço reservado e não usado em volta do <i>Desfazer</i> e do cabeçalho. Com ele devolvido, as <b>placas e os números cresceram</b> sem nada sair da tela.</li>' +
        '<li><b>💡 As dicas saíram de cena por enquanto:</b> elas estavam desatualizadas e apareciam por cima do que você queria ver. Ficam desligadas até serem reescritas direito — nada foi perdido.</li>' +
      '</ul>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:1px solid var(--border-color);border-radius:12px;padding:14px 16px;">' +
      '<div style="font-weight:800; color:#67e8f9; font-size:1rem; margin-bottom:8px;">🌳 v1.6 — Chave enxuta, repescagem justa, histórico grande do letzplay e o treino do relógio contando <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Julho, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>🌳 Chave mínima, sem folga de graça:</b> a chave agora nasce do <b>tamanho real</b> do torneio, em vez de inflar até a próxima potência de 2. Com 12 duplas são 6 jogos, depois 3, 2 e a final — e o <b>último inscrito nunca folga</b>. Da 2ª rodada em diante a chave fecha redonda, sem BYE no meio do caminho.</li>' +
        '<li><b>🎟️ Repescagem justa e transparente:</b> a vaga de repescagem fica <b>vazia até a rodada inteira fechar</b> — nada de nome provisório que troca depois. Quem volta é o <b>melhor derrotado</b> segundo os critérios de desempate <b>do próprio organizador</b>, e a chave se corrige sozinha ao ser aberta.</li>' +
        '<li><b>⏱️ Quem chega depois entra na hora:</b> inscrição tardia (sozinho ou em dupla) vira <b>jogo de verdade</b> na mesma hora, na chave de cima e com o pouso certo na de baixo. Marcar presença depois do sorteio <b>sempre</b> gera o confronto — nunca mais fica ninguém de fora sem aviso.</li>' +
        '<li><b>🤝 Duplas sem mistura:</b> ninguém mais entra em duas duplas ao mesmo tempo. <b>Desfazer dupla</b> voltou a funcionar (antes falhava calado), desinscrever um dos dois <b>mantém o parceiro</b> como individual, e quem entra na chave passa a contar como inscrito de fato.</li>' +
        '<li><b>🧹 Chave mais limpa de ler:</b> BYE não vira mais card — a rodada mostra só confrontos verdadeiros, e o nome da rodada conta só os <b>jogos reais</b>. O avanço de fase parou de perguntar "Ajuste de Chaveamento" quando não há o que ajustar.</li>' +
        '<li><b>⌚ O treino do relógio agora CONTA:</b> a partida vira <b>exercício registrado</b> — no iPhone vai pro app Saúde (conta nos anéis de atividade) e no Android é gravado no <b>Health Connect</b>, entrando nos seus exercícios e na atividade diária. O relógio mostra os <b>batimentos ao vivo</b> durante o jogo e o esforço não é mais descartado no fim da partida. Os batimentos ficam no <b>alto do mostrador</b>, dentro de uma marca colorida pela <b>faixa de queima</b> (5 faixas, do azul ao vermelho) — dá pra ver o esforço de relance, sem tirar os olhos do placar.</li>' +
        '<li><b>⌚ Escolher quem saca, no pulso:</b> na tela de início, tocar num nome já <b>acende a escolha</b> (moldura na cor do time e a bolinha da modalidade ao lado) e tocar em outro troca — a confirmação sai no <b>Iniciar</b>. O mesmo vale na pergunta do <b>2º sacador</b>, entre o primeiro e o segundo game. Antes o toque não dava sinal nenhum de que tinha sido registrado.</li>' +
        '<li><b>📚 Histórico grande do letzplay agora vem inteiro:</b> trazer um histórico com centenas de jogos parava no meio e não gravava nada — funcionava só com perfis pequenos. Agora a leitura <b>não tem prazo</b>: ela vai até o fim, grava o que já leu a cada torneio e a cada punhado de páginas, e se o letzplay pedir uma pausa ela <b>continua sozinha de onde parou</b>, sem você clicar de novo. Testado com 472 e com 2.000 jogos. O botão virou <b>Suspender</b>: o que veio fica guardado e a próxima leitura retoma do ponto exato.</li>' +
        '<li><b>👑 Aceitar co-organização funciona (e dá pra tentar de novo):</b> o convite de co-organização estava sendo <b>recusado pelo servidor</b> pra todo convidado com conta — o organizador recebia "aceitou" e o card continuava em "Pendente de aceite". Agora o aceite passa pelo servidor de verdade, e os botões <b>Aceitar / Recusar</b> ficam na notificação <b>enquanto o convite estiver pendente</b>: se algo falhar, você responde de novo em vez de perder o convite.</li>' +
        '<li><b>🎾 Só conta como jogo o que foi jogado:</b> no histórico e na ficha do atleta, agora só aparece partida <b>com placar</b> — jogo apenas sorteado deixou de contar. Cada card mostra <b>parceiro e adversário</b> (antes aparecia "—", e às vezes a própria pessoa do outro lado), o placar sai do lado certo e vitória não é mais confundida com derrota. Torneios de teste do desenvolvedor não entram em estatística de ninguém.</li>' +
        '<li><b>⏸️ Torneio abandonado para de ocupar a tela:</b> torneio que ficou sem placar novo é <b>encerrado automaticamente</b> — e o organizador é avisado <b>48h antes</b>, com o que resolve: preencher as datas de início e término mantém o torneio ativo. Encerrar assim <b>não fecha a classificação</b> (sem pódio, sem título, sem troféu) e o organizador pode <b>reabrir</b> a qualquer momento informando as datas, pra concluir normalmente. Pontos Corridos nunca é encerrado por isso — é temporada contínua. Torneio que nunca teve nenhum jogo simplesmente sai da vitrine, sem ser encerrado.</li>' +
        '<li><b>🗑️ Apagar um torneio apaga tudo dele:</b> os placares de um torneio apagado continuavam guardados e voltavam a aparecer no histórico das pessoas, como se o torneio ainda existisse. Agora somem junto.</li>' +
        '<li><b>🧽 Apagar informação do perfil agora vale:</b> esvaziar um campo do perfil (data de nascimento, cidade, gênero, modalidades, locais, CEPs) e salvar <b>apaga de verdade</b> — antes a informação voltava na próxima vez que você abria o perfil. A proteção que impede o perfil de sumir sozinho continua de pé: só apaga o que <b>você</b> apagou na tela.</li>' +
        '<li><b>📅 O convite mostra até quando o torneio vai:</b> em torneio com <b>duas fases</b>, o convite compartilhado (WhatsApp, e-mail, folheto) mostrava só as datas da <b>fase classificatória</b> — parecia que o torneio acabava antes da eliminatória começar. Agora a fase eliminatória tem o seu próprio <b>Término da fase</b> no criador de torneios, e o convite passa a mostrar a janela inteira: do início da classificatória ao fim da eliminatória. Em branco, nada muda — o torneio termina junto com a classificatória, como antes. O término pode ser ajustado <b>com a eliminatória já rolando</b>, pra estender ou antecipar o fim.</li>' +
        '<li><b>⚥ A etiqueta "Misto" só aparece quando é verdade:</b> o card do torneio marcava <b>Misto</b> mesmo quando todos os inscritos eram do mesmo gênero. Agora, em <b>misto obrigatório</b> (times 50/50) a etiqueta continua sempre — é a regra do torneio. Fora isso, ela só aparece quando os inscritos estão em <b>proporção exata de 1 para 1</b>; sem isso, nenhuma etiqueta de misto no card.</li>' +
        '<li><b>📅 A janela do torneio é sempre do primeiro dia ao último:</b> não importa quantas fases o torneio tenha — a data mostrada vai do <b>começo mais cedo</b> ao <b>término mais tarde</b> entre todas elas. Antes, duas telas do app podiam discordar sobre quando o torneio acaba: quando o organizador informava só o <b>dia</b> do término (sem hora), um lugar entendia meio-dia e outro entendia o fim do dia — 12 horas de diferença. Agora vale sempre o <b>fim do dia</b>, e existe uma única regra por trás de todas as telas.</li>' +
        '<li><b>📅 O torneio termina quando a ELIMINATÓRIA termina:</b> em torneio com duas fases, tudo que anuncia o encerramento mostrava a data da <b>fase classificatória</b> — o card do torneio, o convite compartilhado, a ficha de regras, o folheto impresso, a planilha exportada, o evento que você adiciona na agenda e a contagem "🏆 Fim do torneio". Agora todos mostram até quando vai a <b>última fase</b>. A fase eliminatória ganhou o seu próprio <b>Término da fase</b> no criador de torneios (ajustável mesmo com ela já rolando, pra estender ou antecipar); em branco, nada muda — o torneio termina junto com a classificatória, como antes. O encerramento automático por inatividade também passou a respeitar esse prazo: torneio com eliminatória marcada pra frente <b>não é mais encerrado</b> enquanto ela não vencer.</li>' +
        '<li><b>💬 Cada grupo tem o SEU grupo de WhatsApp:</b> quem clicava em <b>Abrir grupo</b> no card do seu grupo caía no grupo de WhatsApp de <b>outro grupo</b> do torneio. O link que uma pessoa salvava era espalhado por todos os grupos, porque o app estava reconhecendo os jogadores pelo <b>nome</b> — e o nome não fica guardado no torneio (a identidade é a sua conta). Agora o grupo é identificado pelo <b>grupo em si</b>, e o link de um nunca encosta no outro. De quebra, a enquete de horário do <b>Combinar jogos</b> volta a poder fechar sozinha quando todos concordam, e o aviso do grupo novo chega a quem joga.</li>' +
        '<li><b>📌 Detalhes que incomodavam:</b> o aviso de "faltam N equipes" gruda no topo ao rolar (não some mais), o card não fica preso na tela se você soltar o arraste no meio, e o "meu jogo" rola até a posição certa sem cortar o topo.</li>' +
      '</ul>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #f59e0b;border-radius:12px;padding:14px 16px;background:rgba(245,158,11,0.08);">' +
      '<div style="font-weight:800; color:#fbbf24; font-size:1rem; margin-bottom:8px;">✨ v1.5 — Entrada tardia madura, busca nas chaves e identidade blindada <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Julho, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>🎾 Entrada tardia sempre entra:</b> na Dupla Eliminatória, quem chega depois do sorteio entra <b>na hora</b> — vira um confronto novo que faz a chave crescer (nunca "passa de BYE" de graça), com repescagem no número ímpar. O painel de chaveamento sumiu pra Eliminatória: potência de 2 é resolvida <b>sozinha</b>; só o resto abre decisão.</li>' +
        '<li><b>🔎 Busca nas chaves e na classificação:</b> nova barra de busca no chaveamento e na tabela — ache seu jogo ou sua posição na hora. E a <b>sua linha aparece em verde</b> (nome e colocação) pra você se achar de relance.</li>' +
        '<li><b>🆔 Identidade pela conta, sem confusão de nomes:</b> excluir inscrito, desfazer dupla e registrar W.O. passam a usar a <b>conta</b> (uid) de cada pessoa — dois homônimos não se misturam, e trocar o nome no perfil não quebra nada. W.O. de time chaveia pelos <b>dois</b> membros.</li>' +
        '<li><b>🏷️ Categorias mais claras:</b> a categoria Misto virou um <b>indicador destacado</b> acima do grid (Fem · Misto · Masc centralizado), em vez de uma coluna solta.</li>' +
        '<li><b>🎯 Tie-break explicado:</b> o resumo do torneio agora diz <b>onde</b> o tie-break entra (5-5 ou 6-6), e o botão do grupo do WhatsApp aparece já no raio padrão.</li>' +
        '<li><b>📱 App iOS reconectado:</b> corrigida a conversa do app iOS com a nuvem (CORS <code>capacitor://</code>) — login e dados voltam a funcionar no aplicativo.</li>' +
      '</ul>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #6366f1;border-radius:12px;padding:14px 16px;background:rgba(99,102,241,0.08);">' +
      '<div style="font-weight:800; color:#a5b4fc; font-size:1rem; margin-bottom:8px;">🏆 v1.4 — Eliminatórias com repescagem redondas, do sorteio ao campeão <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Julho, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>🎾 Repescagem como deve ser:</b> a Dupla Eliminatória usa a <b>árvore mínima</b> (chaves superior e inferior espelhadas, sem BYE artificial) e quem chega atrasado entra <b>na hora</b>: o jogo novo nasce contra o <b>melhor derrotado</b> da 1ª rodada — já definido, sem "a definir" pendurado. Chegou um segundo atrasado antes do jogo acontecer? Os dois se enfrentam e o repescado <b>volta pro jogo original dele</b> na chave inferior.</li>' +
        '<li><b>⚖️ Desempate visível:</b> empate de saldo e pontos entre derrotados resolve pela <b>ordem dos jogos na tela</b> — o critério que o organizador consegue conferir olhando a chave.</li>' +
        '<li><b>🤝 Lista de espera viva:</b> formar dupla na espera coloca o time <b>direto na chave</b>, sem re-sortear e sem mexer em nenhum jogo existente; a chave inferior se reorganiza sozinha e nunca "some". Cada pessoa é reconhecida pela <b>conta</b> (uid) — ninguém entra duas vezes, nem com nome trocado.</li>' +
        '<li><b>📋 Presença de torneio estável:</b> marcações em rajada não se atropelam mais (cada toque grava só o próprio campo), com cores canônicas — <b>verde</b> presente, <b>azul</b> confirmado, âmbar "falta um da dupla".</li>' +
        '<li><b>🖥️ Sorteio 100% no servidor:</b> o sorteio, a formação de duplas e a integração de atrasados rodam na nuvem com tela de processamento — sem depender do celular do organizador, e o Cancelar restaura o elenco exatamente como estava.</li>' +
        '<li><b>🎯 Tie-break configurável</b> por torneio (dispara em 5-5 ou 6-6) valendo no placar ao vivo e no lançamento de resultado.</li>' +
        '<li><b>⏱️ Estimativa honesta:</b> a duração prevista do torneio conta <b>equipes efetivas</b> (14 duplas = chave de 14), não pessoas nem inscrições soltas.</li>' +
      '</ul>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #25D366;border-radius:12px;padding:14px 16px;background:rgba(37,211,102,0.08);">' +
      '<div style="font-weight:800; color:#4ade80; font-size:1rem; margin-bottom:8px;">🎾 v1.3 — Torneio ao vivo, grupo do WhatsApp e presença <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Julho, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>💬 Grupo do WhatsApp completo:</b> o organizador cria o grupo oficial e <b>notifica todos os inscritos</b> — no app, por e-mail (com o botão <b>"Entrar no grupo"</b>) e no celular; o e-mail chega em <b>todos</b> os seus e-mails vinculados. O botão de entrar fica na cara, ao lado do "Desinscrever-se", e o card mostra <b>quando</b> foi a última notificação.</li>' +
        '<li><b>📋 Chamada direto na tela do torneio:</b> marcar Presente/Ausente e W.O. no próprio card do inscrito, com a contagem presa no topo. E <b>você mesmo marca sua presença</b>: fica <b>verde (presente)</b> se o GPS confirmar que está no local, <b>azul (confirmado)</b> se for um "eu venho" — e o check-in no local vira presente sozinho.</li>' +
        '<li><b>🆔 Cada pessoa reconhecida pela conta, não pelo nome:</b> presença, aprovação de placar em duplas e os jogos do sorteio passam a usar a <b>identidade</b> de cada um — dois homônimos não se confundem mais, e trocar o nome no perfil não quebra os jogos.</li>' +
        '<li><b>🚫 Faltou alguém da dupla?</b> O desfecho do W.O. é <b>combinado entre os times</b> — puxar suplente, seguir com "Jogador X" ou desclassificar; o adversário aceita ou rejeita, e o organizador decide se não houver acordo.</li>' +
        '<li><b>📡 Placar ao vivo melhor:</b> escolha o 1º sacador com um toque (e o 2º entre os games), tudo cabendo na tela; o tie-break dispara no game certo conforme a pontuação do torneio.</li>' +
        '<li><b>📝 Controle da fase ao vivo:</b> a eliminatória herda a inscrição que você abriu na fase inicial, e dá pra abrir/fechar suplentes e novos confrontos a qualquer momento; a 1ª rodada é sempre R1.</li>' +
        '<li><b>⏱️ Estimativa de duração</b> abaixo da regressiva, detalhe do torneio mais limpo e <b>lembrete confiável</b> (1 semana, 2 dias e no dia, enviado pelo servidor).</li>' +
      '</ul>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #8b5cf6;border-radius:12px;padding:14px 16px;background:rgba(139,92,246,0.08);">' +
      '<div style="font-weight:800; color:#a78bfa; font-size:1rem; margin-bottom:8px;">💬 v1.2 — WhatsApp no app e recuperação de conta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Julho, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>💬 Grupo do WhatsApp entra no app:</b> grupo do jogo (os jogadores do confronto) e grupo oficial do torneio, sem expor o telefone de ninguém — você cria o grupo, cola o link e todo mundo entra num toque. Favoritos e torneios ocultados passam a seguir a sua conta em qualquer aparelho.</li>' +
        '<li><b>📵 O app parou de mandar mensagem por WhatsApp</b> (o número foi bloqueado): seus avisos vão por notificação no app e e-mail. O toggle "WhatsApp" do perfil virou "<b>aceito ser chamado no WhatsApp</b>", e o login por celular passou a ser só por SMS.</li>' +
        '<li><b>🔑 Esqueceu a senha e o e-mail não chega?</b> Voltou o "<b>Redefinir por celular</b>" (código por SMS), e o app avisa quando o provedor costuma segurar o e-mail (Hotmail, Outlook, UOL…).</li>' +
        '<li><b>👥 A lista de inscritos mostra todo mundo</b> — organizador inscrito inclusive — com cada pessoa identificada pela conta, não por e-mail ou nome.</li>' +
        '<li><b>⏱️ Relógio e número do jogo corretos:</b> regressiva pro sorteio na Liga/Pontos Corridos, e o "Jogo N" bate com o do chaveamento.</li>' +
        '<li><b>↺ Restaurar o padrão sugerido</b> (pontuação e critérios de desempate) com um clique, e novo <b>WhatsApp do desenvolvedor</b>.</li>' +
      '</ul>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #f59e0b;border-radius:12px;padding:14px 16px;background:rgba(245,158,11,0.08);">' +
      '<div style="font-weight:800; color:#fbbf24; font-size:1rem; margin-bottom:8px;">⌚ v1.1 — Placar no relógio e letzplay <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Julho, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>⌚ Placar no relógio (Apple Watch e Wear OS):</b> controle o placar ao vivo do pulso — ponto de cada time, desfazer, resolver empates e jogar de novo no casual; o relógio espelha o celular em tempo real e instala junto com o app do telefone.</li>' +
        '<li><b>🎾 letzplay mais fiel:</b> os jogos importados mostram o <b>nome real do torneio</b>, quem foi verificado aparece <b>verde na hora</b>, a busca preenche o perfil do inscrito e respeita o ritmo do letzplay (não trava nem "conclui" sem trazer nada), com <b>cronômetro na tela</b> e busca completa de todos os inscritos num job só.</li>' +
        '<li><b>📊 Histórico mais interessante:</b> veja <b>com quem</b> e <b>contra quem</b> você mais joga, com seu aproveitamento ao lado — e data certa em qualquer fuso.</li>' +
        '<li><b>📱 Verificar celular por SMS</b> voltou a funcionar, e ao reinstalar o app dá pra <b>unir contas</b> em vez de bloquear por nome repetido.</li>' +
        '<li><b>⚡ Espertezas do dia a dia:</b> a partida casual lembra sua última configuração, o check-in sugere a última modalidade, quem "autorizou" o letzplay aparece em violeta na análise, e um W.O. contestado avisa a organização inteira.</li>' +
      '</ul>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #38bdf8;border-radius:12px;padding:14px 16px;background:rgba(56,189,248,0.08);">' +
      '<div style="font-weight:800; color:#7dd3fc; font-size:1rem; margin-bottom:8px;">🏷️ v1.0 — Importe o letzplay, estatísticas e feedback <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Julho, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>🎾 Traga seu histórico do letzplay:</b> uma extensão do Chrome importa seus jogos pro scoreplace, unificados no seu Histórico com os nomes reais de parceiros e adversários.</li>' +
        '<li><b>📊 Estatísticas repaginadas:</b> gráfico de <b>Forma</b> com janela temporal e filtros, e Top parceiros/adversários somando letzplay + scoreplace lado a lado.</li>' +
        '<li><b>🗂️ Análise de Inscritos anti-gato:</b> matriz Gênero × Categoria com cada nome pintado pela verificação do letzplay, criação de categorias direto da matriz, e o <b>rigor da inscrição</b> (de Casual a Oficial) — sinalizando pra subir só quem realmente domina uma categoria mais fácil.</li>' +
        '<li><b>📳 Vibração no toque</b> e <b>🔊 sons nos momentos-chave</b> (sortear, iniciar a partida, fechar game/set, vencer), com liga/desliga no perfil.</li>' +
      '</ul>' +
    '</div>';
  return html;
})();
