// scoreplace.app — Release notes (lazy-loaded)
// Loaded on demand when the user opens "Notas de versões" in help modal.
//
// Convenção de versão (a partir de 30 Abr 2026): MAJOR.MINOR.PATCH-channel.
//
// ⚠️ NOTAS RESUMIDAS POR VERSÃO NATIVA (a partir de jul/2026, pedido do dono):
// as notas mostradas ao usuário são CONSOLIDADAS no nível da versão nativa/loja
// (MINOR — 1.0, 1.1, 1.2, 1.3…) — UMA nota-resumo por minor, com os destaques
// agrupados por tema. NÃO ter mais nota detalhada por patch (1.x.y). Cada patch
// bumpado no dia continua no changelog técnico (git/commits); aqui o usuário vê o
// resumo da versão que foi/vai pra loja. Ao promover um novo minor, dobrar os
// destaques dos patches daquele ciclo num único bloco.
//
// Histórico completo da fase alpha → beta exportado pra
// docs/scoreplace_relatorio_alpha_to_beta.docx (registro local do dono).
// Histórico completo da fase beta → 1.0 (385 notas, 29 Abr → 13 Jul 2026)
// exportado pra docs/scoreplace_relatorio_beta_to_1.0.docx — a partir da v1.0
// o app mostra só as notas de 1.0 em diante.

window._RELEASE_NOTES_HTML = (function () {
  var html =
    // ⚠️ 1.8.27 NÃO ganhou item nesta nota, e isso é DECISÃO, não esquecimento. Conferido
    // no diff: em js/, css/ e index.html ela mexeu SÓ em cache-buster, no
    // `SCOREPLACE_VERSION` e no snapshot do prerender — zero comportamento novo (o commit
    // foi varredura da safe-area + leitura do Sentry, ou seja verificação). O que era
    // visível daquele ciclo já está descrito nos itens do cabeçalho e da tela de carregando,
    // escritos em 1.8.25/1.8.26. A trava (check-release-notes) pega OMISSÃO e não sabe
    // julgar isso — então a justificativa fica aqui, pro próximo leitor não achar que
    // faltou.
    // ⚠️ 1.8.53 e 1.8.54 NÃO ganharam item, e também é DECISÃO. A 1.8.53 acrescentou uma
    // bifurcação ao criar Sandbox (cópia do estado atual × zerada) e a 1.8.54 a REMOVEU
    // inteira, no mesmo dia, a pedido do dono — "vc apontou bem e eu errei… a bifurcação é
    // desnecessária por redundância inútil". Saldo líquido pro usuário: ZERO (conferido no
    // diff: tournaments-organizer.js voltou ao estado anterior). Descrever as duas seria
    // anunciar uma escolha que não existe na tela. A trava (check-release-notes) pega
    // OMISSÃO e não sabe julgar isso — a justificativa fica aqui.
    // ⚠️ 1.8.57 NÃO ganhou item, e é DECISÃO. Ela unificou a LEITURA de "onde estão os
    // jogos desta fase" — phaseComplete e pendingMatches varriam os 3 storages cada uma
    // (o comentário do código chamava a segunda de "espelho" da primeira) e passaram a ler
    // por phaseGames. Saldo pro usuário: ZERO, e provado — os três goldens (motor da R1,
    // eliminatória gerada e construtor) saem IDÊNTICOS, que é o gate do deploy. Anunciar
    // "unificamos uma varredura interna" seria ruído numa nota que o usuário lê pra saber
    // o que mudou pra ele. A trava pega OMISSÃO e não sabe julgar isso — o motivo fica aqui.
    // ── v1.8 ─────────────────────────────────────────────────────────────────
    '<div style="margin-bottom:1rem;border:2px solid #a78bfa;border-radius:12px;padding:14px 16px;background:rgba(167,139,250,0.08);">' +
      '<div style="font-weight:800; color:#c4b5fd; font-size:1rem; margin-bottom:8px;">\uD83C\uDFC5 v1.8 \u2014 Sua coloca\u00e7\u00e3o calculada, conta duplicada que o app pergunta antes, e o app s\u00f3 abre quando terminou de carregar <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Agosto, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        // \u26a0\ufe0f 1.8.67 tem uma 4\u00aa mudan\u00e7a que N\u00c3O ganhou item, e \u00e9 DECIS\u00c3O: o torneio SANDBOX
        // (o "(SB) \u2026", que s\u00f3 o desenvolvedor enxerga) deixou de entrar em "Novidades" e em
        // "Seus \u00faltimos resultados". Ele \u00e9 um clone do torneio real, ent\u00e3o duplicava cada
        // jogo na tela inicial de quem o criou \u2014 e ningu\u00e9m mais no app chega a ver um SB.
        // Anunciar isso seria descrever, pra todo mundo, um sintoma que s\u00f3 existia pra uma
        // pessoa. A trava (check-release-notes) pega OMISS\u00c3O e n\u00e3o sabe julgar isso \u2014 o
        // motivo fica aqui.
        '<li><b>\ud83d\udce3 \u201cNovidades no seu torneio\u201d mostra o lan\u00e7amento de HOJE, mesmo antes de ser confirmado:</b> a se\u00e7\u00e3o s\u00f3 mostrava jogo com o resultado <b>j\u00e1 confirmado pelos dois lados</b> \u2014 e como a confirma\u00e7\u00e3o pode demorar horas, o topo continuava exibindo um jogo da v\u00e9spera com o torneio andando naquele momento. Agora o placar aparece <b>assim que \u00e9 lan\u00e7ado</b>, no topo da lista, marcado como <b>PENDENTE \u00b7 \u23f3 Aguardando aprova\u00e7\u00e3o</b> e dizendo quem lan\u00e7ou \u2014 ou seja, voc\u00ea v\u00ea o que acabou de acontecer sem confundir com resultado final. Se depois for contestado, a se\u00e7\u00e3o mostra isso tamb\u00e9m.</li>' +
        '<li><b>\ud83d\udcf1 \u201cNovidades no seu torneio\u201d passou a ocupar a tela inteira:</b> os jogos eram desenhados <b>um por linha</b>, ent\u00e3o em tela larga sobrava metade da tela vazia \u2014 bem ao lado de \u201cSeus \u00faltimos resultados\u201d, que j\u00e1 usava a largura toda. Agora as duas se\u00e7\u00f5es seguem a mesma regra: <b>1, 2 ou 3 jogos por linha</b> conforme o tamanho da tela.</li>' +
        '<li><b>\ud83c\udfbe O placar do tie-break aparece tamb\u00e9m enquanto o resultado espera aprova\u00e7\u00e3o:</b> um set decidido no tie-break \u00e9 mostrado como <b>6\u207d\u2077\u207e</b> depois de confirmado \u2014 mas, enquanto estava <b>aguardando a confirma\u00e7\u00e3o do outro lado</b>, o card exibia s\u00f3 <b>5</b> e <b>6</b> secos. Os pontos do tie-break estavam gravados desde o lan\u00e7amento; era a tela que n\u00e3o os lia. Agora quem confere o placar v\u00ea o mesmo n\u00famero que vai ficar registrado.</li>' +
        '<li><b>\ud83d\udccd Quem marcou presen\u00e7a aparece VERDE na classifica\u00e7\u00e3o do grupo:</b> na tabela do seu grupo, quem tocou em \u201cCheguei\u201d ganha uma bolinha verde e o nome pintado de verde \u2014 d\u00e1 pra ver de relance <b>quem j\u00e1 est\u00e1 no local e quem falta</b>. Antes a \u00fanica pista era o pontinho de presen\u00e7a <i>por time</i> no card do jogo, que n\u00e3o dizia qual das duas pessoas tinha chegado.</li>' +
        '<li><b>\ud83e\udeaa A ficha do jogador parou de esconder os bot\u00f5es sob o rel\u00f3gio do iPhone:</b> ao tocar no nome de algu\u00e9m, o cabe\u00e7alho da ficha (Voltar + amizade) abria <b>colado no topo da tela</b>, embaixo do rel\u00f3gio/sinal/bateria \u2014 e ali o toque nem chega (o iPhone reserva essa faixa pro sistema), ent\u00e3o o Voltar parecia quebrado. Agora o cabe\u00e7alho desce pra baixo dessa faixa e os bot\u00f5es respondem. <i>(No app instalado; tamb\u00e9m vale pro nativo na pr\u00f3xima atualiza\u00e7\u00e3o das lojas.)</i></li>' +
        '<li><b>\ud83d\udcc5 O bot\u00e3o \u201cCombinar jogos\u201d parou de alargar quando chega proposta:</b> o numerinho de propostas ficava ao lado do texto e esticava o bot\u00e3o, empurrando o \u201ceditar\u201d do grupo de WhatsApp pro lado. Agora o n\u00famero mora no canto de baixo, ao lado de \u201cjogos\u201d, e o texto fica alinhado \u00e0 esquerda \u2014 o bot\u00e3o tem a mesma largura com ou sem propostas.</li>' +
        '<li><b>\u231a Preparo para o rel\u00f3gio jogar sozinho:</b> o app passou a aceitar o <b>di\u00e1rio de jogo</b> do rel\u00f3gio \u2014 a lista de pontos, desfazimentos e trocas de saque registrados <b>no pulso</b>, que chega ao celular quando os dois se falam de novo. \u00c9 a base para o rel\u00f3gio funcionar com o celular na bolsa ou bloqueado (hoje ele depende do celular acordado a cada toque, que foi o que travou a partida no torneio). O placar oficial continua sendo calculado pelo celular, exatamente como sempre. <i>(Sem efeito vis\u00edvel ainda \u2014 o rel\u00f3gio s\u00f3 passa a usar isso na pr\u00f3xima atualiza\u00e7\u00e3o do app nas lojas.)</i></li>' +
        '<li><b>\u21b6 D\u00e1 pra desfazer o \u00faltimo ponto MESMO com a partida terminada:</b> no placar ao vivo, um toque acidental no ponto final encerrava a partida e n\u00e3o havia caminho de volta \u2014 a tela de fim n\u00e3o oferecia o Desfazer. Agora oferece: o jogo <b>reabre</b> no placar de antes do ponto, voc\u00ea segue jogando e, quando terminar de verdade, o resultado corrigido \u00e9 o que fica gravado \u2014 na chave do torneio e no seu hist\u00f3rico, <b>sem duplicar</b> nada.</li>' +
        '<li><b>\u231a O rel\u00f3gio n\u00e3o fica mais preso na tela de fim de set:</b> quando o app do celular recarregava (o que acontece a cada atualiza\u00e7\u00e3o ou reabertura), o rel\u00f3gio podia <b>descartar em sil\u00eancio</b> tudo o que chegava depois e congelar no resultado antigo \u2014 mesmo com o jogo seguinte j\u00e1 rolando no celular. O placar que viaja pro rel\u00f3gio agora carrega a identifica\u00e7\u00e3o da sess\u00e3o, e o rel\u00f3gio reconhece o recome\u00e7o na hora. <i>(Chega ao pulso na pr\u00f3xima atualiza\u00e7\u00e3o do app nas lojas.)</i></li>' +
        '<li><b>\u2665 Batimento no rel\u00f3gio: leitura mais viva e faixas calibr\u00e1veis:</b> a leitura do BPM passou a vir direto do sensor em cad\u00eancia de treino (antes fazia uma volta que atrasava e perdia os picos \u2014 voc\u00ea sentia 160+ e a tela mostrava o vale de segundos atr\u00e1s), e o perfil ganhou o campo opcional <b>\u2665 FC m\u00e1xima</b>: preenchido, ele calibra as 5 faixas de queima com a SUA frequ\u00eancia real, no lugar da f\u00f3rmula gen\u00e9rica 220 \u2212 idade. <i>(A leitura nova chega ao pulso na pr\u00f3xima atualiza\u00e7\u00e3o do app nas lojas; o campo do perfil j\u00e1 vale.)</i></li>' +
        '<li><b>\ud83d\uddc4\ufe0f Torneios novos passam a guardar os jogos num lugar s\u00f3:</b> por hist\u00f3ria, os jogos da <b>fase classificat\u00f3ria</b> eram guardados num lugar e os da <b>chave</b> em outro \u2014 e cada corre\u00e7\u00e3o no motor tinha que ser feita duas vezes, com risco de uma delas ficar diferente. Agora <b>torneio novo</b> guarda tudo no mesmo lugar. Os torneios que j\u00e1 existem <b>n\u00e3o s\u00e3o movidos</b> \u2014 nada do que j\u00e1 foi sorteado ou jogado \u00e9 tocado \u2014 e continuam funcionando exatamente como antes. Pra voc\u00ea, nada muda na tela: os dois formatos passaram a ser desenhados de forma id\u00eantica.</li>' +
        '<li><b>\ud83c\udfb2 O \u201csorteio\u201d como crit\u00e9rio virou a ORDEM DA CHAVE \u2014 e a classifica\u00e7\u00e3o parou de mudar sozinha:</b> quando o desempate chegava no \u201csorteio\u201d, o app tirava um n\u00famero <b>aleat\u00f3rio na hora</b> \u2014 ou seja, a mesma classifica\u00e7\u00e3o podia aparecer numa ordem a cada vez que a tela era desenhada. Agora vale a <b>ordem em que as pessoas aparecem na chave</b>: quem est\u00e1 num jogo mais cedo conta como sorteado antes. \u00c9 est\u00e1vel e, principalmente, <b>confer\u00edvel</b> \u2014 qualquer participante olha a chave e entende por que ficou naquela posi\u00e7\u00e3o.</li>' +
        '<li><b>\ud83c\udfc1 Entre quem caiu na MESMA fase, valem os seus crit\u00e9rios:</b> na elimin\u00e1toria, a ordem entre os eliminados na mesma rodada seguia uma regra fixa que terminava em <b>ordem alfab\u00e9tica</b> \u2014 o acaso do nome decidindo coloca\u00e7\u00e3o. Agora seguem os <b>crit\u00e9rios de desempate que voc\u00ea configurou</b>, como no resto do torneio.</li>' +
        '<li><b>\ud83d\udcca Buchholz e Sonneborn-Berger passam a valer tamb\u00e9m no Rei/Rainha:</b> esses dois crit\u00e9rios podiam ser escolhidos na configura\u00e7\u00e3o, mas nos torneios de Rei/Rainha n\u00e3o tinham efeito \u2014 a tabela n\u00e3o os calculava. Agora calcula, com a mesma f\u00f3rmula da Fase de Grupos.</li>' +
        '<li><b>\ud83c\udf82 Quem preencheu a data de nascimento leva vantagem sobre quem omitiu:</b> nos crit\u00e9rios <b>antiguidade</b> e <b>juventude</b>, quando s\u00f3 uma das pessoas tem a data no perfil, <b>ela passa na frente</b> \u2014 nos dois crit\u00e9rios, inclusive no de \u201cmais novo\u201d. Quem deixou em branco n\u00e3o \u00e9 beneficiado pela omiss\u00e3o. S\u00f3 quando <b>nenhum dos dois</b> preencheu \u00e9 que o crit\u00e9rio n\u00e3o decide e a disputa passa pro pr\u00f3ximo.</li>' +
        '<li><b>\ud83c\udd94 O confronto direto passou a identificar as pessoas pela conta em TODOS os formatos:</b> na <b>Fase de Grupos</b> ele ainda casava pelo nome escrito \u2014 o \u00faltimo lugar do app que fazia isso. Nome muda quando algu\u00e9m se renomeia e se repete entre hom\u00f4nimos, ent\u00e3o o crit\u00e9rio podia cair na pessoa errada. Agora \u00e9 sempre pela conta, como no resto do app.</li>' +
        '<li><b>\u2696\ufe0f Os crit\u00e9rios de desempate que voc\u00ea configurou passam a valer em TODAS as fases:</b> a tela de <b>Crit\u00e9rios de Desempate</b> deixa o organizador escolher quais valem, em que ordem, e tirar os que n\u00e3o quer. Isso j\u00e1 era respeitado nos torneios de <b>Pontos Corridos</b> e <b>Fase de Grupos</b> \u2014 mas a tabela do <b>Rei/Rainha</b> e a ordem que decide <b>quem sobe pra eliminat\u00f3ria</b> usavam uma sequ\u00eancia fixa, ignorando a sua configura\u00e7\u00e3o. Agora vale o que voc\u00ea configurou, em qualquer fase e em qualquer formato. <b>E o \u201cconfronto direto\u201d passou a olhar quem venceu quem de verdade</b>, identificando as pessoas pela conta (e n\u00e3o pelo nome escrito, que muda quando algu\u00e9m se renomeia).</li>' +
        '<li><b>\ud83c\udf82 \u201cMais velho\u201d e \u201cmais novo\u201d voltam a desempatar de verdade:</b> quem escolhia <b>antiguidade</b> ou <b>juventude</b> como crit\u00e9rio n\u00e3o via efeito nenhum \u2014 em nenhum torneio, em nenhuma fase. O app lia a data de nascimento num formato e o perfil a guardava em outro, ent\u00e3o a data simplesmente n\u00e3o era entendida e o crit\u00e9rio era pulado em sil\u00eancio. Agora \u00e9 lida nos dois formatos. \u26a0\ufe0f Quem n\u00e3o tem data de nascimento no perfil continua sem ser desempatado por ela \u2014 o app <b>nunca chuta</b> uma idade.</li>' +
        '<li><b>\ud83e\uddee A tabela e a chave passam a usar a MESMA ordem:</b> a classifica\u00e7\u00e3o que voc\u00ea v\u00ea na tela e a ordem que decide <b>quem sobe pra fase eliminat\u00f3ria</b> eram calculadas por <b>duas regras diferentes</b> \u2014 a da tela desempatava por sets, games, tie-breaks e aproveitamento; a da eliminat\u00f3ria parava antes e, no empate, mantinha a ordem em que os grupos foram lidos. Na pr\u00e1tica: dava pra estar na frente na tabela e ficar atr\u00e1s na hora de montar a chave. Agora \u00e9 <b>uma regra s\u00f3</b>, e o que est\u00e1 na tela \u00e9 o que vale. <b>Nenhum torneio em andamento muda</b> \u2014 conferido contra os dados reais: os classificados continuam os mesmos.</li>' +
        '<li><b>\ud83c\udd94 A fase de grupos passa a guardar QUEM \u00e9 cada pessoa, como o resto do app j\u00e1 fazia:</b> nos torneios com <b>fase de grupos</b>, os jogos eram gravados s\u00f3 com o nome escrito no dia do sorteio \u2014 enquanto os torneios de Rei/Rainha j\u00e1 guardavam a <b>identidade</b> de cada jogador desde o sorteio. Na pr\u00e1tica: quem trocasse o nome no perfil continuaria aparecendo com o antigo nos jogos e na tabela do grupo. Agora as duas formas gravam igual, e o nome mostrado vem sempre do perfil. <b>Nenhum confronto muda</b> \u2014 os grupos e os jogos s\u00e3o exatamente os mesmos; mudou o que fica guardado junto. Quem joga sem conta continua entrando normalmente, identificado pelo nome.</li>' +
        '<li><b>\ud83c\udfd7\ufe0f A elimin\u00e1toria pode come\u00e7ar por uma rodada que FORMA as duplas \u2014 agora tamb\u00e9m depois de uma classificat\u00f3ria:</b> j\u00e1 dava pra fazer um torneio que <b>abre direto na elimin\u00e1toria com uma rodada Rei/Rainha</b> (grupos de 4 em que as duplas se formam pelo resultado). Mas essa op\u00e7\u00e3o <b>desaparecia</b> se o torneio tivesse fase classificat\u00f3ria \u2014 ent\u00e3o o arranjo mais natural de todos n\u00e3o existia: jogar a classificat\u00f3ria, e s\u00f3 os <b>classificados</b> fazerem a rodada que define as duplas da elimin\u00e1toria. Agora existe, e a coloca\u00e7\u00e3o da classificat\u00f3ria vale de verdade: os melhores viram <b>cabe\u00e7as de chave</b> e caem em grupos diferentes, em vez de se encontrarem logo. O torneio passa a ter tr\u00eas etapas \u2014 classificat\u00f3ria \u2192 forma\u00e7\u00e3o das duplas \u2192 elimin\u00e1toria.</li>' +
        '<li><b>\ud83c\udfaf A fase eliminat\u00f3ria passa a saber <i>quem</i> \u00e9 cada pessoa, n\u00e3o s\u00f3 o nome escrito:</b> quando a fase de grupos termina e o app monta a chave eliminat\u00f3ria, cada confronto era gravado apenas com o <b>nome do jeito que estava escrito no dia do sorteio</b>. Quem trocasse o nome no perfil depois continuaria aparecendo com o antigo justamente na chave que decide o campe\u00e3o \u2014 e o app n\u00e3o teria como corrigir sozinho. Agora cada lado do confronto guarda a <b>identidade</b> de quem joga, ent\u00e3o o nome mostrado vem sempre do perfil, atualizado. Os confrontos e a classifica\u00e7\u00e3o continuam <b>exatamente os mesmos</b>: mudou o que fica guardado, n\u00e3o quem joga contra quem. Vale tamb\u00e9m para a <b>tabela do grupo</b>, que passou a mostrar o nome atual mesmo em grupos antigos.</li>' +
        '<li><b>\ud83c\udfc5 \u201cSeus \u00faltimos resultados\u201d mostra mesmo os 3 mais recentes:</b> a lista da tela inicial j\u00e1 cortava em tr\u00eas \u2014 o problema era a <b>ordem</b>. Jogos aprovados pelo caminho normal (uma dupla prop\u00f5e, a outra confirma) entravam na lista como se n\u00e3o tivessem hora nenhuma e perdiam a vez para partidas <b>bem mais antigas</b>. Resultado: voc\u00ea acabava de jogar e a lista continuava mostrando um jogo de semanas atr\u00e1s. Agora vale a hora em que o resultado foi <b>confirmado</b>, para todo mundo.</li>' +
        '<li><b>\ud83d\udd12 Jogo j\u00e1 encerrado n\u00e3o aceita placar novo:</b> uma partida com resultado <b>j\u00e1 confirmado</b> ainda podia receber uma proposta de placar de quem estava jogando \u2014 e a partida reabria como se o resultado estivesse em d\u00favida. Agora, com o jogo encerrado, o app avisa que o placar j\u00e1 foi confirmado e orienta a <b>falar com o organizador</b>, que \u00e9 quem pode corrigir. Organizador e \u00e1rbitro seguem podendo ajustar normalmente.</li>' +
        '<li><b>\u26a1 Publicar uma versão nova deixou de custar uma tela branca:</b> quando sai uma atualização, o app troca para a versão nova — e até agora ele fazia isso do jeito mais radical possível: <b>apagava tudo o que tinha guardado no seu aparelho</b> e recarregava do zero. Resultado: na <b>primeira vez que você abria o app depois de cada publicação</b>, ele precisava buscar mais de cem arquivos pela internet antes de conseguir desenhar qualquer coisa — e você via a tela branca. Como são várias publicações por dia, isso acontecia bastante. Agora a troca é uma <b>passagem de bastão</b>: a versão nova fica pronta em segundo plano e só então assume, <b>sem jogar fora o que já estava guardado</b>. A tela de carregando aparece na hora, como em qualquer outra abertura.</li>' +
        '<li><b>📊 “Seus últimos resultados” passou a ocupar a tela inteira:</b> os cards tinham uma largura máxima fixa, então quando cabia <b>uma coluna só</b> sobrava tela vazia do lado. Agora eles seguem a mesma regra do resto do app: 1, 2, 3 ou 4 colunas conforme o tamanho da tela, sempre ocupando toda a largura.</li>' +
        '<li><b>🔙 O “Voltar” limpa a busca:</b> se você tinha digitado algo na barra de busca e saía da tela pelo <b>Voltar</b>, o filtro continuava valendo por baixo — você voltava para uma lista filtrada por um texto que não aparecia em lugar nenhum, e a tela parecia vazia sem explicação. Agora sair pelo Voltar zera a busca.</li>' +
        '<li><b>📣 “Novidades no seu torneio” só mostra torneio em andamento:</b> torneio já encerrado não popula mais a seção — novidade é o que está acontecendo, e um torneio antigo com dezenas de jogos afogava o que está em curso. O card também passou a ser <b>o mesmo card da chave</b> (foto de cada pessoa, os dois lados da dupla e o subplacar do tie-break), em vez de um desenho próprio só ali.</li>' +
        '<li><b>🙋 O W.O. mostra o nome do perfil, avisa o grupo, e o botão diz o que faz:</b> ao escolher quem faltou, a lista mostrava o <b>nome gravado no dia do sorteio</b> — quem tinha trocado de nome aparecia com o antigo. Agora o nome vem do perfil, vivo. Além disso, ao decretar o W.O. <b>todo o grupo e o substituto passam a ser avisados</b> na hora (antes só o ausente sabia), e o botão diz <b>“Colocar”</b> em vez de um rótulo genérico.</li>' +
        '<li><b>📐 Todo card da chave tem a mesma largura:</b> um jogo com placar <i>pendente</i> era desenhado mais estreito que os vizinhos da mesma coluna (medido: 280px contra 400px). O limite que causava isso não tinha mais razão de existir — os três estados agora saem idênticos.</li>' +
        '<li><b>\u2696\ufe0f O substituto do W.O. respeita a propor\u00e7\u00e3o de g\u00eanero do grupo:</b> ao dar W.O., quem assume a vaga continua vindo da lista de espera \u2014 mas agora o app busca <b>manter a propor\u00e7\u00e3o do torneio</b> (ex.: 25/75, 1 homem e 3 mulheres por grupo). Num grupo s\u00f3 de mulheres, um homem na fila <b>passa na frente</b> e o grupo que estava 0/100 vira 25/75; num grupo que j\u00e1 tem seu homem, \u00e9 a mulher da fila que entra. Em empate, vale a <b>ordem de chegada</b>, como sempre \u2014 e se ningu\u00e9m na fila melhora a propor\u00e7\u00e3o, o primeiro entra do mesmo jeito: a propor\u00e7\u00e3o nunca deixa vaga aberta. O di\u00e1logo de confirma\u00e7\u00e3o diz com todas as letras quando algu\u00e9m entrou na frente da fila e por qu\u00ea.</li>' +
        '<li><b>\ud83d\udce3 Nova se\u00e7\u00e3o \u201cNovidades no seu torneio\u201d:</b> na tela inicial, entre <b>Seu pr\u00f3ximo jogo</b> e <b>Seus \u00faltimos resultados</b>, agora aparecem os <b>\u00faltimos jogos dos outros</b> nos torneios em que voc\u00ea est\u00e1 inscrito \u2014 do mais recente para o mais antigo, pela hora em que o resultado foi lan\u00e7ado. Vem <b>fechada</b>, mostrando s\u00f3 o jogo mais recente; tocando no t\u00edtulo voc\u00ea v\u00ea os anteriores. Jogos que ainda n\u00e3o foram jogados n\u00e3o entram. Quem acabou de se inscrever e ainda n\u00e3o jogou tamb\u00e9m v\u00ea \u2014 \u00e9 justamente quem quer acompanhar.</li>' +
        '<li><b>\ud83c\udfbe O placar do tie-break agora fica registrado e todo mundo v\u00ea:</b> os pontos do tie-break passam a aparecer <b>junto do placar</b>, em cima e entre par\u00eanteses \u2014 um set decidido no tie-break aparece como <b>6\u207d\u2077\u207e</b> em vez de s\u00f3 <b>6</b>. Antes eles podiam ser digitados e <b>sumir na hora de aprovar</b> o resultado, e nem a lista de resultados da tela inicial os mostrava. Vale para quem lan\u00e7ou, para o advers\u00e1rio e para qualquer pessoa que abrir o jogo depois.</li>' +
        '<li><b>\ud83c\udfbe O tie-break tamb\u00e9m aparece ao <i>corrigir</i> um placar j\u00e1 lan\u00e7ado:</b> quando algu\u00e9m j\u00e1 tinha proposto um resultado e o jogo estava <b>aguardando aprova\u00e7\u00e3o</b>, abrir esse placar para ajustar mostrava s\u00f3 os dois n\u00fameros \u2014 os campinhos dos <b>pontos do tie-break</b> n\u00e3o apareciam de jeito nenhum, nem redigitando o placar. Era o \u00fanico caminho em que eles nunca chegavam a existir na tela, ent\u00e3o o placar era salvo <b>sem</b> o tie-break. Agora eles aparecem assim que o placar for o do gatilho (6-5 na regra 5-5, 7-6 na regra 6-6) \u2014 inclusive j\u00e1 abertos ao entrar, quando a proposta que chegou j\u00e1 era um placar de tie-break. Vale para <b>organizador e participantes</b>, na chave e na lista \u201cMeus Resultados\u201d da tela inicial.</li>' +
        '<li><b>\ud83c\udfbe O campo do tie-break volta a abrir no 6-5:</b> ao lan\u00e7ar o placar de um set decidido no tie-break, digitar <b>6-5</b> deixou de abrir os campinhos roxos onde se anotam os <b>pontos do tie-break</b> \u2014 eles s\u00f3 apareciam no 7-6. Acontecia s\u00f3 nos torneios criados pelo <b>atalho r\u00e1pido</b> (o \u201c+Novo Torneio\u201d que j\u00e1 cria com um toque): ali a modalidade era gravada junto com o \u00edcone (\u201c\ud83c\udfbe Beach Tennis\u201d em vez de \u201cBeach Tennis\u201d), e por causa desse detalhe o app deixava de reconhecer o esporte e aplicava a regra do t\u00eanis (tie-break no 6-6, set 7-6) em vez da regra do Beach Tennis (tie-break no 5-5, set 6-5). A pr\u00f3pria tela de configura\u00e7\u00e3o desses torneios j\u00e1 dizia \u201cTie-break em 5-5\u201d \u2014 ou seja, a configura\u00e7\u00e3o prometia 6-5 e o lan\u00e7amento exigia 7-6. Agora o \u00edcone \u00e9 s\u00f3 enfeite da lista: o esporte \u00e9 reconhecido igual das duas formas, os torneios que j\u00e1 existem passam a funcionar <b>sem precisar mexer em nada</b>, e os novos j\u00e1 nascem gravados certo. Quem escolheu a regra na m\u00e3o (5-5 ou 6-6) continua com a sua escolha valendo.</li>' +
        '<li><b>\ud83d\udd11 Entrar ficou dif\u00edcil de errar \u2014 Google e Apple no topo, e o app lembra como voc\u00ea entrou:</b> muita gente voltava depois de um tempo, n\u00e3o lembrava como tinha entrado e acabava <b>criando uma segunda conta</b> sem querer. O login foi reorganizado: <b>Entrar com Google</b> e <b>Entrar com a Apple</b> agora v\u00eam primeiro, o bot\u00e3o que voc\u00ea usou da \u00faltima vez ganha a marca <b>\u201c\u2713 da \u00faltima vez\u201d</b>, e ao digitar um e-mail que j\u00e1 tem conta o app responde na hora <b>como aquela conta entra</b> \u2014 antes de voc\u00ea errar a senha e cair no cadastro. Se voc\u00ea tentar entrar por um caminho novo com um e-mail que j\u00e1 existe, ele oferece <b>conectar os dois \u00e0 mesma conta</b> em vez de criar outra.</li>' +
        '<li><b>\u2709\ufe0f Um e-mail registra como voc\u00ea entra \u2014 e confirma quando algo muda:</b> ao criar a conta voc\u00ea recebe um e-mail com a <b>foto da sua conta</b> (nome, e-mail, celular e as formas de entrar) \u2014 guarde-o: quando n\u00e3o lembrar como entrou, \u00e9 s\u00f3 buscar \u201cscoreplace\u201d na sua caixa. Quando nome, e-mail ou celular mudam, chega uma <b>confirma\u00e7\u00e3o</b> com os dados atualizados. Quem j\u00e1 tem conta recebe o seu uma \u00fanica vez nesta leva. E o app passa a sugerir cadastrar o <b>celular</b>: \u00e9 a forma mais segura de recuperar seu acesso (e o que nos deixa perceber uma conta duplicada antes de ela atrapalhar torneio).</li>' +
        '<li><b>\ud83d\udcdd Inscri\u00e7\u00e3o sem recusa silenciosa \u2014 e sem bloqueio falso em torneio aberto:</b> havia respostas do servidor que a tela <b>engolia</b>: o organizador inscrevia algu\u00e9m com a rodada j\u00e1 sorteada e a pessoa ia pra <b>lista de espera sem nenhuma mensagem</b> (parecia que tinha sumido); inscri\u00e7\u00e3o recusada podia ficar por cima de um aviso de sucesso; e a pergunta <b>\u201cessa conta \u00e9 sua?\u201d</b> da detec\u00e7\u00e3o de conta duplicada nem chegava a abrir em um dos caminhos. Agora <b>todo desfecho tem resposta na tela</b>. E a regra de \u201cinscri\u00e7\u00f5es abertas\u201d virou <b>uma s\u00f3</b>, a mesma do servidor \u2014 fim do caso em que uma temporada com inscri\u00e7\u00f5es abertas bloqueava a inscri\u00e7\u00e3o (ou se fechava sozinha) por causa de um prazo antigo.</li>' +
        '<li><b>\u1fa79 Se o app carregar quebrado, ele se conserta sozinho:</b> \u00e0s vezes um arquivo do app chega <b>pela metade</b> no celular (conex\u00e3o que oscila no meio do download) e fica guardado assim \u2014 o app abre com peda\u00e7os faltando, bot\u00f5es que n\u00e3o respondem, e continua assim mesmo fechando e abrindo. Agora, quando isso acontece, o app percebe, <b>joga fora o que ficou guardado e recarrega uma vez</b>, sozinho. Acontece uma vez s\u00f3 por sess\u00e3o, pra nunca virar recarga em loop.</li>' +
        '<li><b>\u1f464 O app pede o sobrenome \u2014 e passa a reconhecer voc\u00ea mesmo com o nome escrito diferente:</b> quem se cadastra s\u00f3 com o primeiro nome (\u201cBet\u00e2nia\u201d, \u201cFabio\u201d) fica f\u00e1cil de confundir com outra pessoa \u2014 e, se criar uma segunda conta escrevendo o nome completo, o app n\u00e3o percebia que era a mesma pessoa. Aconteceu de verdade: algu\u00e9m acabou <b>em dois grupos do mesmo torneio</b>. Agora o perfil <b>sugere</b> (sem obrigar) que voc\u00ea coloque tamb\u00e9m o sobrenome, e a checagem de conta repetida passa a enxergar o caso \u201cBet\u00e2nia\u201d \u00d7 \u201cMaria Bet\u00e2nia Roberto Faria\u201d \u2014 mas s\u00f3 quando aquele nome \u00e9 <b>raro</b> na base e n\u00e3o \u00e9 sobrenome de outra pessoa, pra n\u00e3o confundir gente diferente que por acaso tem o mesmo primeiro nome. Como sempre, o app <b>pergunta</b> se \u00e9 voc\u00ea \u2014 nunca junta nada sozinho.</li>' +
        '<li><b>\u1f6aa O bot\u00e3o \u201cEntrar\u201d responde ao primeiro toque \u2014 inclusive logo depois de uma atualiza\u00e7\u00e3o:</b> quando o app se atualizava, ele voltava para a tela inicial e o bot\u00e3o <b>Entrar</b> ficava sem reagir: dava para clicar v\u00e1rias vezes <b>sem nada acontecer e sem nenhum aviso</b>. A tela inicial aparece imediatamente, mas o resto do app ainda estava sendo baixado \u2014 e, como a atualiza\u00e7\u00e3o limpa o que estava guardado no aparelho, essa espera ficava longa justamente ali. Agora o toque <b>sempre</b> responde: o bot\u00e3o avisa que est\u00e1 entrando e <b>guarda o seu toque</b>, abrindo a tela de login sozinho assim que o app termina de subir. Voc\u00ea n\u00e3o precisa tocar de novo.</li>' +
        '<li><b>\u1f4cb Entrar na lista de espera voltou a funcionar:</b> em torneio j\u00e1 sorteado, quem clicava para se inscrever via o pr\u00f3prio nome <b>aparecer na lista de espera e sumir logo em seguida</b>, com um erro de permiss\u00e3o \u2014 e ningu\u00e9m entrava na fila. O motivo: para acrescentar <b>uma</b> pessoa numa lista, o app tentava regravar o <b>torneio inteiro</b> a partir do celular, e bastava um detalhe da c\u00f3pia local estar diferente da do servidor para a grava\u00e7\u00e3o toda ser recusada. Agora a entrada na fila \u00e9 feita <b>no servidor</b>, como todos os outros caminhos de inscri\u00e7\u00e3o: ele l\u00ea o torneio atualizado e grava s\u00f3 a lista. O nome tamb\u00e9m deixou de aparecer antes da confirma\u00e7\u00e3o \u2014 era isso que dava a impress\u00e3o de ter entrado e sa\u00eddo.</li>' +
        '<li><b>\u26a1 O app abre na hora \u2014 acabou a tela branca da abertura:</b> abrir o app pelo \u00edcone deixava a tela <b>completamente branca por v\u00e1rios segundos</b> antes de a tela de carregando aparecer, e na segunda vez era mais r\u00e1pido. O motivo estava numa camada que roda <b>antes</b> de qualquer coisa poder ser desenhada: ela buscava arquivos <b>em outro servidor</b> toda vez que o app era aberto do zero, e s\u00f3 depois disso o app come\u00e7ava a ser montado \u2014 no 4G, com o celular acordando a antena, isso custava os segundos de tela branca. Agora essa camada n\u00e3o depende mais de rede nenhuma, e o app passa a ser <b>montado a partir do que j\u00e1 est\u00e1 no seu aparelho</b>: a tela de carregando aparece imediatamente, com internet lenta ou sem internet. As notifica\u00e7\u00f5es e a atualiza\u00e7\u00e3o autom\u00e1tica para a vers\u00e3o nova continuam funcionando igual.</li>' +
        '<li><b>\u23f3 O bot\u00e3o \u201cEntrar\u201d agora avisa que est\u00e1 entrando \u2014 e continua avisando:</b> o feedback existia, mas durava menos de <b>um piscar</b> (medido: sumia em 60 mil\u00e9simos de segundo), ent\u00e3o na pr\u00e1tica era como n\u00e3o existir \u2014 e quem tocava ficava clicando de novo achando que nada tinha acontecido. Agora o bot\u00e3o fica em <b>\u201cEntrando\u2026\u201d</b>, cinza e travado contra toques repetidos, <b>at\u00e9 a tela de login aparecer de verdade</b>. Se ela n\u00e3o abrir, ele avisa em vez de simplesmente voltar ao normal, que era o sil\u00eancio que fazia parecer defeito.</li>' +
        '<li><b>\u2194\ufe0f Bot\u00f5es da ficha do atleta alinhados \u00e0 direita:</b> na ficha, quando o nome \u00e9 comprido, <b>Voltar</b> e <b>Puxar hist\u00f3rico completo</b> passam para a linha de baixo \u2014 e apareciam encostados \u00e0 esquerda, desalinhados do resto. Agora ficam \u00e0 direita nos dois casos, cabendo tudo numa linha ou n\u00e3o.</li>' +
        '<li><b>\u2709\ufe0f Entrou por um convite e criou a conta? J\u00e1 est\u00e1 inscrito:</b> quem chega por um <b>link de convite de torneio</b> e <b>cria a conta ali</b> passa a ser inscrito na hora \u2014 sem precisar procurar o bot\u00e3o \u201cInscrever-se\u201d depois. V\u00e1rias pessoas se cadastravam e paravam no meio do caminho achando que j\u00e1 estavam dentro. O convite hoje j\u00e1 mostra <b>de que torneio se trata</b> antes do clique, ent\u00e3o d\u00e1 pra decidir com a informa\u00e7\u00e3o na m\u00e3o; e a inscri\u00e7\u00e3o vem com um aviso dizendo que <b>voc\u00ea pode se desinscrever a qualquer momento</b> nessa mesma p\u00e1gina. Vale s\u00f3 pra <b>conta nova vinda de convite</b>: quem j\u00e1 tem conta continua entrando pelo bot\u00e3o, e ningu\u00e9m \u00e9 inscrito por s\u00f3 abrir a p\u00e1gina de um torneio.</li>' +
        '<li><b>\ud83c\udfc1 Torneio terminado deixa de dizer \u201cclassifica\u00e7\u00e3o parcial\u201d \u2014 e a sua coloca\u00e7\u00e3o aparece na ficha:</b> num torneio j\u00e1 encerrado, com todas as equipes posicionadas, a classifica\u00e7\u00e3o ainda se anunciava como <b>parcial</b>. Agora quem decide \u00e9 o pr\u00f3prio resultado: fechou quando <b>todo mundo que entrou em quadra</b> tem posi\u00e7\u00e3o \u2014 quem ficou na <b>lista de espera</b> n\u00e3o entra na conta, e quem levou <b>W.O.</b> mant\u00e9m a coloca\u00e7\u00e3o, porque jogou. Enquanto a final ou a disputa de 3\u00ba estiverem em aberto, ela continua dizendo parcial, como deve. Junto com isso, a <b>ficha do atleta</b> passou a mostrar a coloca\u00e7\u00e3o nos torneios <b>daqui</b> (\u201c7\u00ba\u201d), que antes s\u00f3 aparecia nos do letzplay \u2014 uma posi\u00e7\u00e3o por dupla, resolvida pelo perfil de cada pessoa.</li>' +
        '<li><b>\ud83c\udfbe Cada linha da ficha diz de onde veio, logo na abertura:</b> o selo <b>LP</b> (letzplay) e o logo do <b>scoreplace</b> sa\u00edram do fim da linha e passaram a abrir cada item, antes da data. Numa lista que mistura as duas origens, dava trabalho descobrir de onde era cada torneio \u2014 o marcador antigo era o mesmo trof\u00e9u nos dois casos. E o t\u00edtulo <b>FERRAMENTAS DO ORGANIZADOR</b>, que estava apagado por cima da foto do local, voltou a ter contraste (sem crescer de tamanho).</li>' +
        '<li><b>\ud83d\udcf1 No celular o app diz por que a leitura do letzplay n\u00e3o roda ali:</b> tocar em \u201cPuxar hist\u00f3rico completo\u201d abre um aviso explicando que a leitura \u00e9 feita por uma extens\u00e3o do Chrome, que s\u00f3 existe no computador. Antes o bot\u00e3o simplesmente n\u00e3o fazia nada. E a categoria oficial parou de exibir o nome do torneio junto (\u201c11\u00ba BT House Open - MASCULINA C\u201d virou \u201cMASCULINA C\u201d).</li>' +
        '<li><b>\ud83e\uddf9 Nome de torneio repetido, e a leitura mais silenciosa:</b> alguns torneios do letzplay chegavam com o nome escrito duas vezes ("TORNEIO RP 2026 - 10 anos - TORNEIO RP 2026 - 10 anos") \u2014 agora aparecem uma vez s\u00f3, inclusive nas leituras j\u00e1 feitas. E a barra de progresso parou de exibir avisos t\u00e9cnicos sobre a leitura: ela mostra o passo em curso e o tempo decorrido, e mais nada.</li>' +
        '<li><b>\ud83e\udde9 Extens\u00e3o nova: o app manda pro caminho que funciona:</b> quando sai uma vers\u00e3o nova da extens\u00e3o do letzplay, a Chrome Web Store leva alguns dias revisando. Nesse intervalo o app parava de importar e mandava voc\u00ea pra loja \u2014 que ainda tinha a vers\u00e3o antiga, e o Chrome respondia \u201cj\u00e1 est\u00e1 atualizada\u201d. Agora, enquanto a revis\u00e3o n\u00e3o sai, ele oferece o download direto \u2014 sem tirar a loja da tela, que continua ali como o destino permanente. Quando a vers\u00e3o sair por l\u00e1, o download some sozinho e o Chrome volta a atualizar tudo automaticamente.</li>' +
        '<li><b>\ud83c\udfc5 At\u00e9 onde voc\u00ea chegou no torneio \u2014 e com quem:</b> a ficha do atleta passa a dizer a <b>coloca\u00e7\u00e3o entre TODOS os participantes</b>, n\u00e3o a posi\u00e7\u00e3o dentro do grupo: Campe\u00e3o, Vice, 3\u00ba/4\u00ba na semifinal, 5\u00ba/7\u00ba nas quartas \u2014 sempre com a fase entre par\u00eanteses e o nome da sua dupla ao lado. Posi\u00e7\u00e3o dentro do grupo ("GRUPO 03 \u00b7 2\u00ba de 3") deixou de aparecer: ela n\u00e3o diz nada sobre o torneio. Quando n\u00e3o d\u00e1 pra apurar a coloca\u00e7\u00e3o geral, a linha fica sem coloca\u00e7\u00e3o \u2014 em ranking, a posi\u00e7\u00e3o continua saindo normalmente, porque ali ela j\u00e1 \u00e9 a classifica\u00e7\u00e3o inteira.</li>' +
        '<li><b>\ud83d\udcac Um bot\u00e3o s\u00f3 para o grupo do torneio no WhatsApp:</b> o grupo geral do evento aparecia em <b>dois lugares</b> \u2014 ao lado de Inscrever-se/Desinscrever-se e de novo nas Ferramentas do Organizador. Ficou <b>um s\u00f3</b>, no topo: quem \u00e9 organizador abre por ele o painel completo (<b>criar, trocar, abrir e compartilhar</b>) e quem est\u00e1 inscrito entra no grupo com um toque. E o t\u00edtulo <b>FERRAMENTAS DO ORGANIZADOR</b> voltou a usar a fonte de t\u00edtulo do app, maior e mais leg\u00edvel.</li>' +
        '<li><b>\ud83c\udfc5 A classifica\u00e7\u00e3o final fecha at\u00e9 o 4\u00ba lugar \u2014 e o W.O. fica no jogo em que aconteceu:</b> em torneios com <b>disputa de 3\u00ba lugar</b>, a classifica\u00e7\u00e3o podia parar no 2\u00ba e pular direto pro 5\u00ba, aparecendo como <b>parcial</b> mesmo com tudo jogado. Agora quem decide o 3\u00ba e o 4\u00ba \u00e9 <b>o jogo que foi disputado</b>. E quem levou W.O. em <b>uma</b> partida deixou de sumir das outras: continua aparecendo nos jogos que jogou.</li>' +
        '<li><b>\ud83d\ude4d Os nomes na chave saem do seu perfil \u2014 e acompanham quando voc\u00ea muda:</b> em torneios de <b>dupla</b>, os cards podiam mostrar <b>\u201cJogador sem perfil (\u2026)\u201d</b> no lugar de todo mundo, mesmo com o torneio e os perfis certos: os nomes eram desenhados antes de os perfis carregarem e ningu\u00e9m os repintava depois. Agora cada nome \u00e9 resolvido pelo <b>perfil do jogador</b> e atualizado assim que ele chega \u2014 inclusive quando a pessoa <b>troca o nome no perfil</b>, sem depender do nome que ficou gravado no dia do sorteio.</li>' +
        '<li><b>\u2705 Leitura completa deixa de aparecer como incompleta:</b> havia perfis em que a leitura terminava, gravava tudo, e mesmo assim a barra parava em 99% e o nome continuava violeta \u2014 <b>reler n\u00e3o resolvia</b>, porque o problema n\u00e3o estava na leitura e sim num contador interno que ficava para tr\u00e1s do que j\u00e1 tinha sido lido. Agora o que vale \u00e9 o <b>acervo</b>: quem tem todas as partidas que a lista do letzplay enumera fecha em 100% e fica verde, sem precisar puxar de novo. Vale tamb\u00e9m para as leituras <b>j\u00e1 gravadas</b>.</li>' +
        '<li><b>\ud83d\udd17 O torneio do scoreplace na sua ficha virou link \u2014 e o Voltar traz voc\u00ea de volta:</b> na ficha do atleta, o nome de um torneio <b>daqui</b> abre a chave dele; o <b>Voltar</b> devolve voc\u00ea exatamente \u00e0 ficha que estava aberta, pra consulta r\u00e1pida sem perder o lugar. A linha tamb\u00e9m passou a mostrar <b>com quem</b> voc\u00ea jogou. E torneio do letzplay que foi lido mas ainda <b>n\u00e3o tem jogos publicados l\u00e1</b> deixou de aparecer mudo: agora ele diz isso, em vez de parecer uma linha quebrada.</li>' +
        '<li><b>\ud83e\udd1d Dupla fixa tem nome; dupla que roda vira \u201cdupla vari\u00e1vel\u201d:</b> em torneio onde a fase de grupos \u00e9 jogada com <b>parceiro rotativo</b> (voc\u00ea joga cada jogo com um), a linha dizia \u201ccom Fulano\u201d \u2014 e Fulano era s\u00f3 <b>o \u00faltimo com quem voc\u00ea jogou</b>. Agora ela diz <b>dupla vari\u00e1vel</b> nesse caso, e continua nomeando a dupla quando ela foi mesmo fixa. Isso tamb\u00e9m corrigiu um erro maior: quem jogou os grupos com parceiros diferentes e depois <b>fixou a dupla e foi campe\u00e3o</b> aparecia como se tivesse parado na fase de grupos.</li>' +
        '<li><b>\ud83d\udd11 A coloca\u00e7\u00e3o passou a aparecer tamb\u00e9m em quem j\u00e1 tinha sido lido:</b> a coloca\u00e7\u00e3o sai da <b>chave do torneio</b>, e a leitura s\u00f3 come\u00e7ou a traz\u00ea-la h\u00e1 poucos dias. Quem foi lido antes disso j\u00e1 contava como \u201clido\u201d, ent\u00e3o a releitura pulava esses torneios e a coloca\u00e7\u00e3o nunca chegava \u2014 na ficha do atleta a maior parte das linhas ficava sem nada. Agora um torneio sem a chave volta a ser aberto <b>uma vez</b> pra busc\u00e1-la; depois disso ele n\u00e3o \u00e9 mais rebuscado. Basta puxar o hist\u00f3rico de novo.</li>' +
        '<li><b>\ud83c\udfbd Sua categoria \u00e9 Masculina ou Feminina \u2014 nunca \u201cMista\u201d:</b> \u201cMista\u201d \u00e9 a categoria do torneio, n\u00e3o do atleta. Quem jogou uma mista aparecia com ela como categoria oficial; agora vale a faixa disputada no pr\u00f3prio g\u00eanero, e quando s\u00f3 existe torneio misto o app mostra apenas o n\u00edvel (D, C+\u2026) em vez de afirmar um g\u00eanero que o dado n\u00e3o diz.</li>' +
        '<li><b>\ud83d\udd22 Seus pontos em destaque:</b> o n\u00famero que resume seu n\u00edvel saiu da letra mi\u00fada ao lado da forma e ganhou um canto pr\u00f3prio, em corpo grande.</li>' +
        '<li><b>\uD83E\uDDE9 A extens\u00e3o do letzplay est\u00e1 na Chrome Web Store:</b> instalar virou <b>um clique</b> e a atualiza\u00e7\u00e3o passou a ser <b>autom\u00e1tica</b> \u2014 acabou o vaiv\u00e9m de baixar zip e reinstalar na m\u00e3o a cada vers\u00e3o. O zip continua existindo como alternativa enquanto a loja revisa uma vers\u00e3o nova.</li>' +
        '<li><b>\uD83D\uDC65 Conta duplicada: o app pergunta antes:</b> se voc\u00ea j\u00e1 tem outra conta aqui, agora ele <b>reconhece o seu nome escrito de outro jeito</b> \u2014 com ponto, sem acento, com a inicial abreviada ou faltando uma letra \u2014 e <b>pergunta antes</b> de deixar voc\u00ea se inscrever duas vezes no mesmo torneio. Se o <b>celular ou o e-mail j\u00e1 autenticado</b> for o mesmo nos dois lados, a\u00ed ele <b>une na hora</b> \u2014 \u00e9 prova de que a conta \u00e9 sua. Fora isso <b>nada \u00e9 unido sozinho</b>: s\u00f3 depois que voc\u00ea confirmar a posse da outra conta, pelo e-mail ou pelo celular dela. E se voc\u00ea disser que n\u00e3o \u00e9 voc\u00ea, ele <b>n\u00e3o pergunta de novo</b> \u2014 s\u00f3 volta a perguntar se aparecer algo mais forte, como o mesmo celular.</li>' +
        '<li><b>\u23F3 O app s\u00f3 abre quando terminou de carregar:</b> antes a tela era liberada <b>por tempo</b>, mesmo com os dados ainda a caminho \u2014 voc\u00ea entrava, ia direto procurar o torneio e a interface <b>travava por alguns segundos</b>. Agora quem libera \u00e9 o <b>dado</b>: a tela inicial aparece quando a dashboard est\u00e1 realmente pronta, e a navega\u00e7\u00e3o j\u00e1 come\u00e7a fluida.</li>' +
        '<li><b>\uD83C\uDFBE Uma tela de carregando só, com a marca e o %:</b> o app tinha <b>cinco</b> telas de “carregando” diferentes — uma aparecia entre o Entrar e a dashboard sem porcentagem nenhuma, e outra, bem mais antiga, ainda surgia no meio do uso (histórico, troféus, ficha do jogador, ferramentas do organizador, locais) como uma bolinha solta com um texto cinza. Agora é <b>uma só, em todo lugar</b>: logo do scoreplace.app, a bola girando, o que está acontecendo e a barra laranja com a <b>porcentagem</b> — que sempre fecha em 100% antes de a tela sair, em vez de congelar no meio.</li>' +
        '<li><b>\uD83D\uDCD0 O cabeçalho voltou pro lugar, e o “Entrar” avisa que entendeu o toque:</b> no celular o topo do app invadia a área do relógio, do sinal e da bateria — também na tela inicial de quem ainda não entrou. A causa era um detalhe de formatação que derrubava, junto, várias regras de layout do celular. Está corrigido, com uma trava automática pra não acontecer de novo. E o botão <b>Entrar</b> passou a mudar de estado assim que você toca: fica cinza com <b>“Entrando…”</b> até a tela de login aparecer, em vez de parecer que o toque não pegou.</li>' +
        '<li><b>\uD83D\uDD0E Busca da chave que acha quem est\u00e1 fora:</b> procurar um nome agora encontra tamb\u00e9m quem est\u00e1 em <b>Desativados</b>, <b>Lista de espera</b> e <b>W.O.</b>, e esconde as caixas que ficaram sem ningu\u00e9m. O <b>cabe\u00e7alho parou de deslizar</b> ao limpar o campo no \u2715, e os cart\u00f5es da <b>Organiza\u00e7\u00e3o</b> passaram a respeitar o filtro \u2014 quem n\u00e3o bate com a busca some junto.</li>' +
        '<li><b>\uD83D\uDCE8 O convite deixou de nascer escondido:</b> ao abrir <b>Convidar</b> num torneio, a primeira linha do painel ficava <b>atr\u00e1s da barra de busca</b>. Agora ele abre logo abaixo do cabe\u00e7alho, inteiro, e rola dentro de si em telas menores.</li>' +
        '<li><b>\uD83D\uDC64 Quem se inscreveu n\u00e3o some mais:</b> se a internet caísse no meio da inscri\u00e7\u00e3o \u2014 4G ruim na quadra, aba fechada \u2014 a tela dizia <b>inscrito</b> e o servidor nunca recebia. A pessoa ficava num limbo: aparecia no elenco, mas <b>fora de qualquer grupo</b> e invis\u00edvel na rodada. Agora a inscri\u00e7\u00e3o s\u00f3 \u00e9 dada como feita quando o <b>servidor confirma</b>, e o app avisa se n\u00e3o conseguiu. Junto disso, um <b>grupo j\u00e1 formado n\u00e3o pode mais desaparecer</b> por um aparelho que estava com a tela aberta h\u00e1 muito tempo.</li>' +
        '<li><b>\uD83D\uDCCD \u201cPlace\u201d virou \u201cPresen\u00e7a\u201d:</b> o bot\u00e3o mudou de nome pra dizer o que ele faz de verdade \u2014 marcar que voc\u00ea est\u00e1 no local. Mesma tela, mesmo lugar.</li>' +
        '<li><b>\uD83E\uDDF9 Verifica\u00e7\u00e3o do letzplay mais honesta:</b> uma leitura s\u00f3 conta como <b>verificada</b> (nome verde) quando foi feita pela <b>vers\u00e3o atual</b> da extens\u00e3o. Leituras antigas voltam a aparecer como <b>autorizadas mas ainda n\u00e3o conferidas</b> at\u00e9 serem puxadas de novo \u2014 antes elas eram tratadas como conferidas mesmo tendo vindo de um motor que j\u00e1 se sabia defeituoso.</li>' +
      '</ul>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #22d3ee;border-radius:12px;padding:14px 16px;background:rgba(34,211,238,0.08);">' +
      '<div style="font-weight:800; color:#67e8f9; font-size:1rem; margin-bottom:8px;">🛡️ v1.7 — Sorteio que não se apaga, contato direto com quem joga com você, e placar validado no servidor <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Agosto, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>🛟 Nada do que já aconteceu se perde:</b> quando duas pessoas mexem no mesmo torneio ao mesmo tempo, o aparelho que estava com a tela aberta há mais tempo podia gravar por cima e <b>apagar o que aconteceu no meio tempo</b>. Agora não apaga mais: <b>inscrição</b>, <b>placar já lançado</b>, <b>rodada recém-sorteada</b>, <b>jogo de quem entrou depois</b>, <b>link do grupo de WhatsApp</b>, <b>horário combinado</b>, <b>substituição por W.O.</b> e <b>aceite de co-organização</b> ficam de pé. O que você quis mudar continua sendo salvo normalmente — só o que ficou para trás é que volta.</li>' +
        '<li><b>🔒 Sorteio realizado não se apaga:</b> depois de sorteado, o chaveamento <b>não é mais destruído</b> para fazer outro — nem por engano, nem com resultados já lançados. Na fase eliminatória a chave é uma árvore fechada e o app recusa; em fase de rodadas, o que existe é <b>gerar uma rodada extra</b>, que acrescenta sem apagar nada do que já foi jogado.</li>' +
        '<li><b>💬 Falar com quem joga com você:</b> na classificação, um botão verde ao lado do nome abre o <b>WhatsApp direto</b> com a pessoa — ou o e-mail, quando ela não tem telefone cadastrado. Todo mundo do seu grupo pode falar com o grupo; o organizador fala com qualquer inscrito, em qualquer classificação.</li>' +
        '<li><b>👤 Ficha do jogador na classificação:</b> tocar no nome na tabela abre a <b>ficha completa</b> — foto, histórico e troféus —, a mesma da Análise de Inscritos. Nos cards da chave o nome deixou de abrir ficha: na quadra, o card é área de toque para lançar placar.</li>' +
        '<li><b>🛡️ Placar validado no servidor:</b> quem pode lançar o resultado de cada jogo passou a ser decidido <b>no servidor</b>, e não só no aparelho — quem está naquele jogo, o que a fase permite, e em que ponto está a negociação entre os times. Na prática você não vê diferença; o que muda é que a regra passa a valer igual para todo mundo.</li>' +
        '<li><b>🚫 W.O. agora é sempre a mesma coisa:</b> quem leva W.O. fica com <b>0 pontos na rodada</b> e vai para os <b>Desativados</b> — não vai mais para a lista de espera. A fila passou a depender de um ato da própria pessoa: quando ela liga o botão <b>Ativado</b> no torneio, entra no <b>fim da lista de espera</b> e volta a jogar quando chegar a vez. O organizador não escolhe mais o destino, e o primeiro da fila continua assumindo a vaga até o fim do torneio.</li>' +
        '<li><b>🔁 O botão “Ativado” não volta mais sozinho:</b> quem estava desativado e ligava o botão via ele <b>voltar para “Desativado”</b> segundos depois, por mais que tentasse. A ativação chegava a ser gravada, mas uma proteção do app — a que impede alguém de sumir do torneio por engano — entendia a ida para a <b>lista de espera</b> como se a pessoa tivesse sido apagada, e desfazia tudo. Agora ir para a fila é reconhecido como o que é: uma <b>mudança de lugar</b>, não um sumiço. E o botão passou a mostrar o seu estado de verdade: estando na fila e disponível, ele fica <b>Ativado</b> — antes dizia “Desativado” mesmo depois de você ligar. Junto disso, <b>reativar tira você da folga</b>: quem estava desativado e voltou passa a aparecer na <b>lista de espera</b>, e não mais entre os <b>Desativados</b> da rodada — inclusive quem já tinha reativado antes desta correção.</li>' +
        '<li><b>⏳ Quem se inscreveu depois do sorteio aparece:</b> a Análise de Inscritos agora mostra também a <b>lista de espera</b>, marcada como tal, para o organizador atribuir gênero e categoria antes de a pessoa entrar. E atribuir gênero <b>fixa de primeira</b> — antes era preciso repetir o processo.</li>' +
        '<li><b>⚖️ Proporção de homens e mulheres no sorteio:</b> em torneios <b>sem categoria por gênero</b> (todo mundo misturado), o organizador escolhe a proporção de cada 4 pessoas sorteadas — <b>50/50</b>, <b>25/75</b> ou <b>75/25</b> — na tela do sorteio equilibrado e também no criar/editar, dentro da fase. Com <b>Travar proporção</b> ligado, um grupo só se forma se a proporção for atendida <b>exatamente</b>, e quem não couber espera; desligado, o sorteio persegue a proporção e, quando não houver mais como mantê-la, <b>flexibiliza para incluir o máximo de gente</b>. Quem está sem gênero declarado <b>nunca é presumido</b> homem ou mulher — e o próprio sorteio deixa você preencher isso ali na hora. Com categorias separadas (Fem, Masc ou Misto) nada disso aparece: ali o sorteio já roda por categoria, e o Misto já é 50/50 por ser sorteio de duplas.</li>' +
        '<li><b>🛡️ Grupo fora da regra não nasce:</b> a composição de cada grupo passou a ser <b>conferida antes de o grupo existir</b>, e não depois. Um grupo que não atenda à proporção travada é recusado na porta em vez de aparecer montado para alguém perceber o erro depois.</li>' +
        '<li><b>🪪 Duas contas da mesma pessoa: o app pergunta antes de virar problema:</b> quando alguém se inscreve com uma conta nova e os sinais indicam que já está naquele torneio por outra (<b>mesmo celular</b> ou <b>mesmo nome</b>), o app avisa que <b>parece</b> ser a mesma pessoa e mostra <b>com qual conta</b> — com e-mail e telefone mascarados —, oferecendo unir as duas ali mesmo. Se não for você, basta dizer: o app <b>não volta a perguntar</b>. Organizador inscrevendo terceiro nunca passa por essa porta.</li>' +
        '<li><b>🔗 Unir contas não perde nada:</b> ao juntar duas contas suas, viajam junto <b>torneios, jogos, presenças, avisos, a leitura do letzplay e os dados do perfil</b> — e os dois logins continuam entrando. Vence a conta <b>mais ativa</b>, que absorve o que só existia na outra.</li>' +
        '<li><b>🏷️ Trocou o nome? Aparece igual em todo lugar:</b> classificação, cards da chave e a <b>busca</b> passaram a mostrar o nome do <b>perfil de agora</b>, e não o que ficou gravado no dia do sorteio. Antes a mesma pessoa podia aparecer com dois nomes em telas diferentes, e procurar pelo nome novo não achava os jogos dela.</li>' +
        '<li><b>🎯 Análise de Inscritos: a mudança vai para a pessoa certa:</b> mexer na categoria ou no gênero de <b>várias pessoas de uma vez</b> agora salva todas — e nunca mais grava no inscrito errado da lista. E ao salvar, os <b>dois botões</b> mostram “Salvando…” até terminar, para você não sair achando que já gravou.</li>' +
        '<li><b>🎾 Placar ao vivo redesenhado:</b> cada dupla virou uma <b>caixa colorida</b> com os nomes, o games/sets e o ponto dentro, e <b>quem saca fica em cima</b> (à esquerda, no celular deitado). Os números cresceram para ocupar a placa inteira, o <b>Desfazer atravessa a base</b> e nada mais encosta nas bordas — feito para ler de longe, com o celular apoiado na quadra.</li>' +
        '<li><b>📐 A tela inteira passou a ser usada:</b> no celular havia uma <b>faixa morta</b> no topo do placar e a placa do ponto <b>cobria o Desfazer</b> — dependendo do aparelho, o botão ficava debaixo do número. Os dois sumiram, no iPhone e no Android.</li>' +
        '<li><b>🏐 “Quem saca primeiro?” cabe numa tela só:</b> os quatro jogadores agora aparecem em <b>duas colunas</b> (seu time à esquerda, o adversário à direita), sem rolar para achar o quarto. O título e o Iniciar foram para o cabeçalho, e o botão Fechar repetido saiu.</li>' +
        '<li><b>⚡ Partida casual: menos rolagem para começar:</b> a modalidade ficou em <b>uma linha só</b> e os botões <b>Sortear Duplas</b> e <b>Rei/Rainha</b> agora ficam <b>lado a lado</b> — sobra tela para os jogadores e para o QR code de convite.</li>' +
        '<li><b>⌚ Relógio: o sacador é o mesmo dos dois lados:</b> ao escolher quem saca <b>no celular</b>, o relógio acende <b>o mesmo nome</b> na hora — antes cada um mostrava um, e dava para começar a partida com sacadores diferentes. E o <b>Encerrar do relógio agora encerra de verdade</b>: fecha o placar no celular, devolve você à tela de configuração e o relógio volta para a espera, em vez de ficar preso na tela do último resultado.</li>' +
        '<li><b>🎾 letzplay: o amistoso conta como jogo:</b> partidas <b>avulsas</b> (sem competição) passaram a entrar na sua leitura como jogo. Antes elas eram descartadas, e a barra ficava eternamente devendo — dizia “concluí” com a conta aberta, e o seu nome não fechava em verde na Análise.</li>' +
        '<li><b>⚖️ Empate em 5-5: você escolhe:</b> ao empatar o set (5-5, 6-6, 7-7…), o app pergunta em tela cheia se quer <b>prorrogar</b> (jogar até 2 games de vantagem) ou <b>ativar o tie-break</b> — números e botões grandes, pra decidir de longe, na quadra. Em partida casual ele pergunta <b>sempre</b>; em torneio vale a regra do organizador.</li>' +
        '<li><b>🎾 No tie-break o sacador continua do mesmo lado:</b> quem saca fica <b>sempre à esquerda</b> (deitado) ou <b>em cima</b> (em pé). Antes o lado congelava justamente no tie-break, que é onde o saque mais troca. Vale igual no relógio.</li>' +
        '<li><b>⌚ O relógio não trava mais ao encerrar:</b> ao tocar em Encerrar no fim da partida, o relógio ficava preso no placar final sem fazer mais nada. Agora ele volta pra uma tela própria.</li>' +
        '<li><b>🙋 Só o primeiro nome no placar:</b> a tela mostra <b>Rodrigo</b>, não <b>Rodrigo Barth</b> — sobra espaço e a fonte cresce. O sobrenome só aparece quando dois jogadores têm o mesmo primeiro nome, e só o quanto basta pra diferenciar.</li>' +
        '<li><b>📏 Placar maior na mesma tela:</b> havia espaço reservado e não usado em volta do <i>Desfazer</i> e do cabeçalho. Com ele devolvido, as <b>placas e os números cresceram</b> sem nada sair da tela.</li>' +
        '<li><b>💡 As dicas saíram de cena por enquanto:</b> elas estavam desatualizadas e apareciam por cima do que você queria ver. Ficam desligadas até serem reescritas direito — nada foi perdido.</li>' +
      '</ul>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:1px solid var(--border-color);border-radius:12px;padding:14px 16px;">' +
      '<div style="font-weight:800; color:#67e8f9; font-size:1rem; margin-bottom:8px;">🌳 v1.6 — Chave enxuta, repescagem justa, histórico grande do letzplay e o treino do relógio contando <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Julho, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>🌳 Chave mínima, sem folga de graça:</b> a chave agora nasce do <b>tamanho real</b> do torneio, em vez de inflar até a próxima potência de 2. Com 12 duplas são 6 jogos, depois 3, 2 e a final — e o <b>último inscrito nunca folga</b>. Da 2ª rodada em diante a chave fecha redonda, sem BYE no meio do caminho.</li>' +
        '<li><b>🎟️ Repescagem justa e transparente:</b> a vaga de repescagem fica <b>vazia até a rodada inteira fechar</b> — nada de nome provisório que troca depois. Quem volta é o <b>melhor derrotado</b> segundo os critérios de desempate <b>do próprio organizador</b>, e a chave se corrige sozinha ao ser aberta.</li>' +
        '<li><b>⏱️ Quem chega depois entra na hora:</b> inscrição tardia (sozinho ou em dupla) vira <b>jogo de verdade</b> na mesma hora, na chave de cima e com o pouso certo na de baixo. Marcar presença depois do sorteio <b>sempre</b> gera o confronto — nunca mais fica ninguém de fora sem aviso.</li>' +
        '<li><b>🤝 Duplas sem mistura:</b> ninguém mais entra em duas duplas ao mesmo tempo. <b>Desfazer dupla</b> voltou a funcionar (antes falhava calado), desinscrever um dos dois <b>mantém o parceiro</b> como individual, e quem entra na chave passa a contar como inscrito de fato.</li>' +
        '<li><b>🧹 Chave mais limpa de ler:</b> BYE não vira mais card — a rodada mostra só confrontos verdadeiros, e o nome da rodada conta só os <b>jogos reais</b>. O avanço de fase parou de perguntar "Ajuste de Chaveamento" quando não há o que ajustar.</li>' +
        '<li><b>⌚ O treino do relógio agora CONTA:</b> a partida vira <b>exercício registrado</b> — no iPhone vai pro app Saúde (conta nos anéis de atividade) e no Android é gravado no <b>Health Connect</b>, entrando nos seus exercícios e na atividade diária. O relógio mostra os <b>batimentos ao vivo</b> durante o jogo e o esforço não é mais descartado no fim da partida. Os batimentos ficam no <b>alto do mostrador</b>, dentro de uma marca colorida pela <b>faixa de queima</b> (5 faixas, do azul ao vermelho) — dá pra ver o esforço de relance, sem tirar os olhos do placar.</li>' +
        '<li><b>⌚ Escolher quem saca, no pulso:</b> na tela de início, tocar num nome já <b>acende a escolha</b> (moldura na cor do time e a bolinha da modalidade ao lado) e tocar em outro troca — a confirmação sai no <b>Iniciar</b>. O mesmo vale na pergunta do <b>2º sacador</b>, entre o primeiro e o segundo game. Antes o toque não dava sinal nenhum de que tinha sido registrado.</li>' +
        '<li><b>📚 Histórico grande do letzplay agora vem inteiro:</b> trazer um histórico com centenas de jogos parava no meio e não gravava nada — funcionava só com perfis pequenos. Agora a leitura <b>não tem prazo</b>: ela vai até o fim, grava o que já leu a cada torneio e a cada punhado de páginas, e se o letzplay pedir uma pausa ela <b>continua sozinha de onde parou</b>, sem você clicar de novo. Testado com 472 e com 2.000 jogos. O botão virou <b>Suspender</b>: o que veio fica guardado e a próxima leitura retoma do ponto exato.</li>' +
        '<li><b>👑 Aceitar co-organização funciona (e dá pra tentar de novo):</b> o convite de co-organização estava sendo <b>recusado pelo servidor</b> pra todo convidado com conta — o organizador recebia "aceitou" e o card continuava em "Pendente de aceite". Agora o aceite passa pelo servidor de verdade, e os botões <b>Aceitar / Recusar</b> ficam na notificação <b>enquanto o convite estiver pendente</b>: se algo falhar, você responde de novo em vez de perder o convite.</li>' +
        '<li><b>🎾 Só conta como jogo o que foi jogado:</b> no histórico e na ficha do atleta, agora só aparece partida <b>com placar</b> — jogo apenas sorteado deixou de contar. Cada card mostra <b>parceiro e adversário</b> (antes aparecia "—", e às vezes a própria pessoa do outro lado), o placar sai do lado certo e vitória não é mais confundida com derrota. Torneios de teste do desenvolvedor não entram em estatística de ninguém.</li>' +
        '<li><b>⏸️ Torneio abandonado para de ocupar a tela:</b> torneio que ficou sem placar novo é <b>encerrado automaticamente</b> — e o organizador é avisado <b>48h antes</b>, com o que resolve: preencher as datas de início e término mantém o torneio ativo. Encerrar assim <b>não fecha a classificação</b> (sem pódio, sem título, sem troféu) e o organizador pode <b>reabrir</b> a qualquer momento informando as datas, pra concluir normalmente. Pontos Corridos nunca é encerrado por isso — é temporada contínua. Torneio que nunca teve nenhum jogo simplesmente sai da vitrine, sem ser encerrado.</li>' +
        '<li><b>🗑️ Apagar um torneio apaga tudo dele:</b> os placares de um torneio apagado continuavam guardados e voltavam a aparecer no histórico das pessoas, como se o torneio ainda existisse. Agora somem junto.</li>' +
        '<li><b>🧽 Apagar informação do perfil agora vale:</b> esvaziar um campo do perfil (data de nascimento, cidade, gênero, modalidades, locais, CEPs) e salvar <b>apaga de verdade</b> — antes a informação voltava na próxima vez que você abria o perfil. A proteção que impede o perfil de sumir sozinho continua de pé: só apaga o que <b>você</b> apagou na tela.</li>' +
        '<li><b>📅 O convite mostra até quando o torneio vai:</b> em torneio com <b>duas fases</b>, o convite compartilhado (WhatsApp, e-mail, folheto) mostrava só as datas da <b>fase classificatória</b> — parecia que o torneio acabava antes da eliminatória começar. Agora a fase eliminatória tem o seu próprio <b>Término da fase</b> no criador de torneios, e o convite passa a mostrar a janela inteira: do início da classificatória ao fim da eliminatória. Em branco, nada muda — o torneio termina junto com a classificatória, como antes. O término pode ser ajustado <b>com a eliminatória já rolando</b>, pra estender ou antecipar o fim.</li>' +
        '<li><b>⚥ A etiqueta "Misto" só aparece quando é verdade:</b> o card do torneio marcava <b>Misto</b> mesmo quando todos os inscritos eram do mesmo gênero. Agora, em <b>misto obrigatório</b> (times 50/50) a etiqueta continua sempre — é a regra do torneio. Fora isso, ela só aparece quando os inscritos estão em <b>proporção exata de 1 para 1</b>; sem isso, nenhuma etiqueta de misto no card.</li>' +
        '<li><b>📅 A janela do torneio é sempre do primeiro dia ao último:</b> não importa quantas fases o torneio tenha — a data mostrada vai do <b>começo mais cedo</b> ao <b>término mais tarde</b> entre todas elas. Antes, duas telas do app podiam discordar sobre quando o torneio acaba: quando o organizador informava só o <b>dia</b> do término (sem hora), um lugar entendia meio-dia e outro entendia o fim do dia — 12 horas de diferença. Agora vale sempre o <b>fim do dia</b>, e existe uma única regra por trás de todas as telas.</li>' +
        '<li><b>📅 O torneio termina quando a ELIMINATÓRIA termina:</b> em torneio com duas fases, tudo que anuncia o encerramento mostrava a data da <b>fase classificatória</b> — o card do torneio, o convite compartilhado, a ficha de regras, o folheto impresso, a planilha exportada, o evento que você adiciona na agenda e a contagem "🏆 Fim do torneio". Agora todos mostram até quando vai a <b>última fase</b>. A fase eliminatória ganhou o seu próprio <b>Término da fase</b> no criador de torneios (ajustável mesmo com ela já rolando, pra estender ou antecipar); em branco, nada muda — o torneio termina junto com a classificatória, como antes. O encerramento automático por inatividade também passou a respeitar esse prazo: torneio com eliminatória marcada pra frente <b>não é mais encerrado</b> enquanto ela não vencer.</li>' +
        '<li><b>💬 Cada grupo tem o SEU grupo de WhatsApp:</b> quem clicava em <b>Abrir grupo</b> no card do seu grupo caía no grupo de WhatsApp de <b>outro grupo</b> do torneio. O link que uma pessoa salvava era espalhado por todos os grupos, porque o app estava reconhecendo os jogadores pelo <b>nome</b> — e o nome não fica guardado no torneio (a identidade é a sua conta). Agora o grupo é identificado pelo <b>grupo em si</b>, e o link de um nunca encosta no outro. De quebra, a enquete de horário do <b>Combinar jogos</b> volta a poder fechar sozinha quando todos concordam, e o aviso do grupo novo chega a quem joga.</li>' +
        '<li><b>📌 Detalhes que incomodavam:</b> o aviso de "faltam N equipes" gruda no topo ao rolar (não some mais), o card não fica preso na tela se você soltar o arraste no meio, e o "meu jogo" rola até a posição certa sem cortar o topo.</li>' +
      '</ul>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #f59e0b;border-radius:12px;padding:14px 16px;background:rgba(245,158,11,0.08);">' +
      '<div style="font-weight:800; color:#fbbf24; font-size:1rem; margin-bottom:8px;">✨ v1.5 — Entrada tardia madura, busca nas chaves e identidade blindada <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Julho, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>🎾 Entrada tardia sempre entra:</b> na Dupla Eliminatória, quem chega depois do sorteio entra <b>na hora</b> — vira um confronto novo que faz a chave crescer (nunca "passa de BYE" de graça), com repescagem no número ímpar. O painel de chaveamento sumiu pra Eliminatória: potência de 2 é resolvida <b>sozinha</b>; só o resto abre decisão.</li>' +
        '<li><b>🔎 Busca nas chaves e na classificação:</b> nova barra de busca no chaveamento e na tabela — ache seu jogo ou sua posição na hora. E a <b>sua linha aparece em verde</b> (nome e colocação) pra você se achar de relance.</li>' +
        '<li><b>🆔 Identidade pela conta, sem confusão de nomes:</b> excluir inscrito, desfazer dupla e registrar W.O. passam a usar a <b>conta</b> (uid) de cada pessoa — dois homônimos não se misturam, e trocar o nome no perfil não quebra nada. W.O. de time chaveia pelos <b>dois</b> membros.</li>' +
        '<li><b>🏷️ Categorias mais claras:</b> a categoria Misto virou um <b>indicador destacado</b> acima do grid (Fem · Misto · Masc centralizado), em vez de uma coluna solta.</li>' +
        '<li><b>🎯 Tie-break explicado:</b> o resumo do torneio agora diz <b>onde</b> o tie-break entra (5-5 ou 6-6), e o botão do grupo do WhatsApp aparece já no raio padrão.</li>' +
        '<li><b>📱 App iOS reconectado:</b> corrigida a conversa do app iOS com a nuvem (CORS <code>capacitor://</code>) — login e dados voltam a funcionar no aplicativo.</li>' +
      '</ul>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #6366f1;border-radius:12px;padding:14px 16px;background:rgba(99,102,241,0.08);">' +
      '<div style="font-weight:800; color:#a5b4fc; font-size:1rem; margin-bottom:8px;">🏆 v1.4 — Eliminatórias com repescagem redondas, do sorteio ao campeão <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Julho, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>🎾 Repescagem como deve ser:</b> a Dupla Eliminatória usa a <b>árvore mínima</b> (chaves superior e inferior espelhadas, sem BYE artificial) e quem chega atrasado entra <b>na hora</b>: o jogo novo nasce contra o <b>melhor derrotado</b> da 1ª rodada — já definido, sem "a definir" pendurado. Chegou um segundo atrasado antes do jogo acontecer? Os dois se enfrentam e o repescado <b>volta pro jogo original dele</b> na chave inferior.</li>' +
        '<li><b>⚖️ Desempate visível:</b> empate de saldo e pontos entre derrotados resolve pela <b>ordem dos jogos na tela</b> — o critério que o organizador consegue conferir olhando a chave.</li>' +
        '<li><b>🤝 Lista de espera viva:</b> formar dupla na espera coloca o time <b>direto na chave</b>, sem re-sortear e sem mexer em nenhum jogo existente; a chave inferior se reorganiza sozinha e nunca "some". Cada pessoa é reconhecida pela <b>conta</b> (uid) — ninguém entra duas vezes, nem com nome trocado.</li>' +
        '<li><b>📋 Presença de torneio estável:</b> marcações em rajada não se atropelam mais (cada toque grava só o próprio campo), com cores canônicas — <b>verde</b> presente, <b>azul</b> confirmado, âmbar "falta um da dupla".</li>' +
        '<li><b>🖥️ Sorteio 100% no servidor:</b> o sorteio, a formação de duplas e a integração de atrasados rodam na nuvem com tela de processamento — sem depender do celular do organizador, e o Cancelar restaura o elenco exatamente como estava.</li>' +
        '<li><b>🎯 Tie-break configurável</b> por torneio (dispara em 5-5 ou 6-6) valendo no placar ao vivo e no lançamento de resultado.</li>' +
        '<li><b>⏱️ Estimativa honesta:</b> a duração prevista do torneio conta <b>equipes efetivas</b> (14 duplas = chave de 14), não pessoas nem inscrições soltas.</li>' +
      '</ul>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #25D366;border-radius:12px;padding:14px 16px;background:rgba(37,211,102,0.08);">' +
      '<div style="font-weight:800; color:#4ade80; font-size:1rem; margin-bottom:8px;">🎾 v1.3 — Torneio ao vivo, grupo do WhatsApp e presença <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Julho, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>💬 Grupo do WhatsApp completo:</b> o organizador cria o grupo oficial e <b>notifica todos os inscritos</b> — no app, por e-mail (com o botão <b>"Entrar no grupo"</b>) e no celular; o e-mail chega em <b>todos</b> os seus e-mails vinculados. O botão de entrar fica na cara, ao lado do "Desinscrever-se", e o card mostra <b>quando</b> foi a última notificação.</li>' +
        '<li><b>📋 Chamada direto na tela do torneio:</b> marcar Presente/Ausente e W.O. no próprio card do inscrito, com a contagem presa no topo. E <b>você mesmo marca sua presença</b>: fica <b>verde (presente)</b> se o GPS confirmar que está no local, <b>azul (confirmado)</b> se for um "eu venho" — e o check-in no local vira presente sozinho.</li>' +
        '<li><b>🆔 Cada pessoa reconhecida pela conta, não pelo nome:</b> presença, aprovação de placar em duplas e os jogos do sorteio passam a usar a <b>identidade</b> de cada um — dois homônimos não se confundem mais, e trocar o nome no perfil não quebra os jogos.</li>' +
        '<li><b>🚫 Faltou alguém da dupla?</b> O desfecho do W.O. é <b>combinado entre os times</b> — puxar suplente, seguir com "Jogador X" ou desclassificar; o adversário aceita ou rejeita, e o organizador decide se não houver acordo.</li>' +
        '<li><b>📡 Placar ao vivo melhor:</b> escolha o 1º sacador com um toque (e o 2º entre os games), tudo cabendo na tela; o tie-break dispara no game certo conforme a pontuação do torneio.</li>' +
        '<li><b>📝 Controle da fase ao vivo:</b> a eliminatória herda a inscrição que você abriu na fase inicial, e dá pra abrir/fechar suplentes e novos confrontos a qualquer momento; a 1ª rodada é sempre R1.</li>' +
        '<li><b>⏱️ Estimativa de duração</b> abaixo da regressiva, detalhe do torneio mais limpo e <b>lembrete confiável</b> (1 semana, 2 dias e no dia, enviado pelo servidor).</li>' +
      '</ul>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #8b5cf6;border-radius:12px;padding:14px 16px;background:rgba(139,92,246,0.08);">' +
      '<div style="font-weight:800; color:#a78bfa; font-size:1rem; margin-bottom:8px;">💬 v1.2 — WhatsApp no app e recuperação de conta <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Julho, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>💬 Grupo do WhatsApp entra no app:</b> grupo do jogo (os jogadores do confronto) e grupo oficial do torneio, sem expor o telefone de ninguém — você cria o grupo, cola o link e todo mundo entra num toque. Favoritos e torneios ocultados passam a seguir a sua conta em qualquer aparelho.</li>' +
        '<li><b>📵 O app parou de mandar mensagem por WhatsApp</b> (o número foi bloqueado): seus avisos vão por notificação no app e e-mail. O toggle "WhatsApp" do perfil virou "<b>aceito ser chamado no WhatsApp</b>", e o login por celular passou a ser só por SMS.</li>' +
        '<li><b>🔑 Esqueceu a senha e o e-mail não chega?</b> Voltou o "<b>Redefinir por celular</b>" (código por SMS), e o app avisa quando o provedor costuma segurar o e-mail (Hotmail, Outlook, UOL…).</li>' +
        '<li><b>👥 A lista de inscritos mostra todo mundo</b> — organizador inscrito inclusive — com cada pessoa identificada pela conta, não por e-mail ou nome.</li>' +
        '<li><b>⏱️ Relógio e número do jogo corretos:</b> regressiva pro sorteio na Liga/Pontos Corridos, e o "Jogo N" bate com o do chaveamento.</li>' +
        '<li><b>↺ Restaurar o padrão sugerido</b> (pontuação e critérios de desempate) com um clique, e novo <b>WhatsApp do desenvolvedor</b>.</li>' +
      '</ul>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #f59e0b;border-radius:12px;padding:14px 16px;background:rgba(245,158,11,0.08);">' +
      '<div style="font-weight:800; color:#fbbf24; font-size:1rem; margin-bottom:8px;">⌚ v1.1 — Placar no relógio e letzplay <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Julho, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>⌚ Placar no relógio (Apple Watch e Wear OS):</b> controle o placar ao vivo do pulso — ponto de cada time, desfazer, resolver empates e jogar de novo no casual; o relógio espelha o celular em tempo real e instala junto com o app do telefone.</li>' +
        '<li><b>🎾 letzplay mais fiel:</b> os jogos importados mostram o <b>nome real do torneio</b>, quem foi verificado aparece <b>verde na hora</b>, a busca preenche o perfil do inscrito e respeita o ritmo do letzplay (não trava nem "conclui" sem trazer nada), com <b>cronômetro na tela</b> e busca completa de todos os inscritos num job só.</li>' +
        '<li><b>📊 Histórico mais interessante:</b> veja <b>com quem</b> e <b>contra quem</b> você mais joga, com seu aproveitamento ao lado — e data certa em qualquer fuso.</li>' +
        '<li><b>📱 Verificar celular por SMS</b> voltou a funcionar, e ao reinstalar o app dá pra <b>unir contas</b> em vez de bloquear por nome repetido.</li>' +
        '<li><b>⚡ Espertezas do dia a dia:</b> a partida casual lembra sua última configuração, o check-in sugere a última modalidade, quem "autorizou" o letzplay aparece em violeta na análise, e um W.O. contestado avisa a organização inteira.</li>' +
      '</ul>' +
    '</div>' +
    '<div style="margin-bottom:1rem;border:2px solid #38bdf8;border-radius:12px;padding:14px 16px;background:rgba(56,189,248,0.08);">' +
      '<div style="font-weight:800; color:#7dd3fc; font-size:1rem; margin-bottom:8px;">🏷️ v1.0 — Importe o letzplay, estatísticas e feedback <span style="color:var(--text-muted); font-weight:400; font-size:0.78rem;">(Julho, 2026)</span></div>' +
      '<ul style="margin:0; padding-left:1.1rem; font-size:0.86rem; line-height:1.5; color:var(--text-main);">' +
        '<li><b>🎾 Traga seu histórico do letzplay:</b> uma extensão do Chrome importa seus jogos pro scoreplace, unificados no seu Histórico com os nomes reais de parceiros e adversários.</li>' +
        '<li><b>📊 Estatísticas repaginadas:</b> gráfico de <b>Forma</b> com janela temporal e filtros, e Top parceiros/adversários somando letzplay + scoreplace lado a lado.</li>' +
        '<li><b>🗂️ Análise de Inscritos anti-gato:</b> matriz Gênero × Categoria com cada nome pintado pela verificação do letzplay, criação de categorias direto da matriz, e o <b>rigor da inscrição</b> (de Casual a Oficial) — sinalizando pra subir só quem realmente domina uma categoria mais fácil.</li>' +
        '<li><b>📳 Vibração no toque</b> e <b>🔊 sons nos momentos-chave</b> (sortear, iniciar a partida, fechar game/set, vencer), com liga/desliga no perfil.</li>' +
      '</ul>' +
    '</div>';
  return html;
})();
