const fs = require('fs');
const s = fs.readFileSync('js/views/tournaments-categories.js', 'utf8');
let fail = 0;
function ok(v, m) { if (v) console.log('✓ ' + m); else { fail++; console.error('✗ ' + m); } }
function body(name, next, prefix) { const a = prefix === 'window.' ? s.indexOf(prefix + name + ' = function(') : s.indexOf((prefix || 'function ') + name + '('); const b = s.indexOf(next, a); return s.slice(a, b); }
const remove = body('_executeRemoveFromCategory', 'window._moveBetweenCategories');
const move = body('_moveBetweenCategories', '// Auto-reassign', 'window.');
const assign = body('_assignParticipantCategory', '// Category assignment notification');
[['remoção', remove], ['movimentação', move]].forEach(([name, code]) => {
  ok(/FirestoreDB\._callFn\('applyEnrollmentAssignments'/.test(code), name + ' despacha a intenção server-side');
  ok(!/AppStore\.commitTournamentTx|saveTournament\(|AppStore\.sync\(/.test(code), name + ' não escreve no navegador');
  ok(/uid: p\.uid/.test(code) && /email: p\.email/.test(code) && /name: p\.displayName/.test(code), name + ' envia identidade estável, nunca o índice da tela');
});
ok(/uncategorizedByOrganizer: true/.test(remove), 'remoção preserva a marca explícita de sem categoria definida pela organização');
ok(/_callFn\('applyEnrollmentAssignments'/.test(assign) && /markWasUncategorized: true/.test(assign) && /notifyCategory: true/.test(assign) && !/AppStore\.commitTournamentTx|saveTournament\(|AppStore\.sync\(/.test(assign), 'atribuição direta só despacha a intenção com marca e aviso canônicos');
const merge = body('_executeMerge', '// Remove a participant');
ok(/_callFn\('mergeTournamentCategories'/.test(merge) && !/AppStore\.commitTournamentTx|saveTournament\(|AppStore\.sync\(/.test(merge), 'mesclagem só despacha a intenção para a Function');
const deleteEmpty = s.slice(s.indexOf('function _applyDeleteEmptyCategory'), s.indexOf('// Unmerge a previously merged category', s.indexOf('function _applyDeleteEmptyCategory')));
ok(/return 'occupied'/.test(deleteEmpty) && /return 'played'/.test(deleteEmpty), 'exclusão mantém as proteções contra categoria ocupada ou com jogos');
ok(/_simplifySingletonCategories\(t\)/.test(deleteEmpty) && /_autoReconcileParticipantCategories\(t\)/.test(deleteEmpty), 'exclusão reaplica a reconciliação completa no documento fresco');
const deleteAction = s.slice(s.indexOf('window._deleteEmptyCategory = function'), s.indexOf('// Unmerge a previously merged category', s.indexOf('window._deleteEmptyCategory = function')));
ok(/_callFn\('deleteEmptyTournamentCategory'/.test(deleteAction) && !/commitTournamentTx|saveTournament\(|AppStore\.sync\(/.test(deleteAction), 'exclusão de categoria só despacha a intenção para a Function');
const unmerge = body('_executeUnmerge', '// Unmerge without mergeHistory');
const inferred = body('_executeInferredUnmerge', '// Assign an uncategorized participant');
ok(/_callFn\('undoTournamentCategoryMerge'/.test(unmerge) && !/AppStore\.commitTournamentTx|saveTournament\(|AppStore\.sync\(/.test(unmerge), 'desfazer histórico só despacha a intenção para a Function');
ok(/_callFn\('undoInferredTournamentCategoryMerge'/.test(inferred) && !/AppStore\.commitTournamentTx|saveTournament\(|AppStore\.sync\(/.test(inferred), 'desfazer inferido só despacha a intenção para a Function');
const autoAssign = s.slice(s.indexOf('window._autoAssignCategories = function'), s.indexOf('// Async version:', s.indexOf('window._autoAssignCategories = function')));
const hydrate = s.slice(s.indexOf('window._hydrateInlineCatMgr = function'), s.indexOf('/* ══ OS CLIQUES', s.indexOf('window._hydrateInlineCatMgr = function')));
const categoryPage = s.slice(s.indexOf('window.renderCategoryManagerPage = function'), s.indexOf('// Central re-render:', s.indexOf('window.renderCategoryManagerPage = function')));
const normalizeRequest = s.slice(s.indexOf('window._requestTournamentCategoryNormalization = function'), s.indexOf('// v2.4.28:', s.indexOf('window._requestTournamentCategoryNormalization = function')));
ok(!/AppStore\.(?:mutate|commitTournamentTx)|saveTournament\(|AppStore\.sync\(/.test(autoAssign) && /_callFn\('autoAssignTournamentCategories'/.test(s), 'autoatribuição só pede a decisão atômica à Function; não persiste no navegador');
ok(/_requestTournamentCategoryNormalization\(tId\)/.test(hydrate) && /_requestTournamentCategoryNormalization\(tId\)/.test(categoryPage) && !/commitTournamentTx|saveTournament\(|AppStore\.sync\(/.test(hydrate + categoryPage), 'renderização só pede normalização canônica; não grava no navegador');
ok(/_callFn\('normalizeTournamentCategories'/.test(normalizeRequest) && !/AppStore\.(?:mutate|commitTournamentTx)|saveTournament\(|AppStore\.sync\(/.test(normalizeRequest), 'pedido de normalização só despacha a intenção para a Function');
const categoryComm = s.slice(s.indexOf('function _categoryCommIdentity'), s.indexOf('// ════════════════════════════════════════════════════════════════════════════\n// Normalização', s.indexOf('function _categoryCommIdentity')));
ok(/_applyCategoryCommUpdates/.test(categoryComm) && /_callFn\('applyCategoryCommunicationMarkers'/.test(categoryComm), 'marcadores de comunicação são gravados pela Function no participante fresco');
ok(!/AppStore\.(?:mutate|commitTournamentTx)|saveTournament\(|AppStore\.sync\(/.test(categoryComm), 'comunicação de categoria não escreve snapshot no navegador');
const resolveRequest = body('_resolveCategoryChange', 'window._approveCategoryChange');
ok(/commitTournamentTx/.test(resolveRequest) && /reqIdentity/.test(resolveRequest) && !/saveTournament\(|AppStore\.sync\(/.test(resolveRequest), 'aprovação de pedido identifica e resolve o pedido fresco');
const profileDirect = body('_applyProfileCategoryDirect', 'window._requestCategoryChangeFromProfile');
ok(/commitTournamentTx/.test(profileDirect) && /freshMe/.test(profileDirect) && !/saveTournament\(|AppStore\.sync\(/.test(profileDirect), 'categoria direta do perfil atualiza o inscrito fresco');
const requestChange = s.slice(s.indexOf('window._requestCategoryChangeFromProfile = function'), s.indexOf('// Helper interno'));
ok(/commitTournamentTx/.test(requestChange) && /changeRequest/.test(requestChange) && !/saveTournament\(|AppStore\.sync\(/.test(requestChange), 'pedido de rebaixamento é inserido no documento fresco');
if (fail) process.exit(1);
