/* Regressão: as abas Ouro/Prata ou Feminina/Masculina são a rota de volta
 * entre linhas da chave. Filtrar uma linha não pode ocultar a própria barra.
 * node tests/chaves-abas-estaveis.test.js */
const fs = require('fs');
const path = require('path');
const src = fs.readFileSync(path.join(__dirname, '..', 'js', 'views', 'bracket.js'), 'utf8');
const routerSrc = fs.readFileSync(path.join(__dirname, '..', 'js', 'router.js'), 'utf8');
const componentsCss = fs.readFileSync(path.join(__dirname, '..', 'css', 'components.css'), 'utf8');
let fail = 0, pass = 0;
function ok(condition, message) {
  if (condition) { pass++; console.log('  ✓ ' + message); }
  else { console.error('  ✗ ' + message); fail++; }
}

ok(src.includes('function _bracketTabsApply'), 'aplicador único mantém o estado da aba');
ok(/\.sticky-back-header::before\s*\{[\s\S]*?z-index:\s*0;[\s\S]*?top:\s*-4px;[\s\S]*?bottom:\s*-4px;/.test(componentsCss), 'a máscara da linha Voltar sobrepõe poucos pixels acima e abaixo, sem criar margem fantasma');
ok(/\.sticky-back-header\s*\{[\s\S]*?box-shadow:\s*0 -2px 0 var\(--bg-darker, #111114\), 0 2px 0 var\(--bg-darker, #111114\);/.test(componentsCss), 'a linha Voltar cobre as emendas de subpixel acima e abaixo sem criar margem');
ok(src.includes('function _bracketTabsAnchor') && src.includes("first.closest('.bracket-sticky-scroll-wrapper, .bracket-scroll-container')"), 'faixa de abas ancora acima do trilho inteiro, não dentro da primeira rodada');
ok(src.includes("gb.style.background = onG ? 'linear-gradient(135deg,#fbbf24,#f59e0b)'"), 'aba principal ativa é visualmente trazida para frente');
ok(src.includes('border-radius:12px 12px 0 0'), 'abas principais usam o recorte de aba de planilha');
ok(!src.includes('[data-bracket-tab-empty="1"]{display:none!important;}'), 'filtro não oculta mais holders estruturais da chave');
ok(!src.includes("p.setAttribute('data-bracket-tab-holder', '1')"), 'montagem não marca ancestrais dos cards como escondíveis');
ok(src.includes("cb.style.display = ownG === gender ? '' : 'none'"), 'subabas só alternam pelo gênero ativo sem remover as abas principais');
ok(src.includes('function _bracketLayoutEliminationTree') && src.includes("data-bracket-tree-lines") && src.includes("cardColumns[ci - 1].length !== cardColumns[ci].length * 2") && src.includes('Nunca tirar um jogo do fluxo da sua coluna'), 'eliminatórias desenham conectores sem tirar cards do fluxo nem aplicar a regra em rodadas independentes');
ok(src.includes("if (phase && phase.kind) return phase.kind === 'elimination';"), 'conectores respeitam a fase canônica e não herdam um rótulo eliminatório legado');
ok(src.includes('function _bracketTabsRefreshRoundRail') && src.includes("rail.hidden = true") && src.includes("rail.innerHTML = ''"), 'não existe uma segunda régua de rodadas concorrendo com a chave');
ok(src.includes('class="bracket-round-heading"') && src.includes('data-bracket-round-heading-portal') && src.includes('function _bracketUpdateRoundHeadingPortal') && src.includes('(root.parentNode || scope).appendChild(portal)') && !src.includes('document.body.appendChild(portal)') && src.includes('document.addEventListener(\'scroll\'') && src.includes('scope && scope.style') && src.includes('function _bracketSyncRoundHeadingOffsets') && src.includes('window._bracketRoundHeadingResizeListener') && src.includes('var(--bg-darker,#111114)') && !src.includes('visibility:hidden!important'), 'a linha e o Ocultar usam um portal fixo sob as abas, no ciclo de vida da seção da chave e sem camadas órfãs');
ok(src.includes('regression_round_portal_overlaps_tabs_subpixel_seam') && src.includes('regression_round_portal_masks_cards_before_round_heading') && src.includes('regression_round_portal_is_hard_clipped_to_tabs_width') && src.includes("top:' + (Math.floor(anchorBottom) - 24) + 'px") && src.includes('overflow:hidden;isolation:isolate;pointer-events:none;z-index:30') && src.includes("clone.style.cssText = 'position:absolute;top:24px;"), 'o portal mascara cards antes do cabeçalho de rodada em tela cheia, fica abaixo das abas e é recortado na largura delas');
ok(src.includes('function _bracketFocusOperationalCard') && src.includes('window._bracketFocusOperationalCard = _bracketFocusOperationalCard') && src.includes('regression_operational_card_focus_has_one_geometry') && src.includes('_bracketFocusOperationalCard(root, nextEntry.card, \'instant\')'), 'a agenda usa uma única geometria de foco para a aba e para os callbacks tardios');
ok(src.includes('z-index:31;isolation:isolate') && src.includes('pointer-events:none;z-index:30'), 'a máscara do portal fica estritamente abaixo da camada interativa das abas');
ok(src.includes('regression_bracket_tabs_do_not_leak_round_content') && src.includes('regression_round_heading_never_overlaps_category_tabs'), 'a correção do portal é complementar às proteções já publicadas da faixa e do cabeçalho');
ok(routerSrc.includes('cleanupBracketRoundHeadingPortals') && routerSrc.includes("document.querySelectorAll('[data-bracket-round-heading-portal]')") && routerSrc.includes('cleanupBracketRoundHeadingPortals();'), 'o roteador remove os portais de cabeçalho antes de toda nova rota');
ok(src.includes('data-bracket-tier-title') && src.includes('tierTitles[ti].hidden = true'), 'a linha ativa não duplica título atrás da aba fixa');
ok(src.includes('function _bracketTabsPlaceSearch(root, searchWrap, force)') && src.includes('getBoundingClientRect') && src.includes('data-bracket-search-slot="inline"') && src.includes('data-bracket-search-slot="stack"') && src.includes('searchWrap.parentNode === target') && !src.includes('window.innerWidth >= 560'), 'a busca escolhe o slot pela largura real do painel, com slots canônicos e sem depender da viewport');
ok(src.includes('function _bracketTabsObserveSearchLayout(root, searchWrap)') && src.includes('root._bracketTabsResizeObserver.disconnect()') && src.includes('if (!root.isConnected)') && src.includes('typeof ResizeObserver !== \'undefined\'') && src.includes('window._bracketTabsFallbackResizeListener'), 'resize do painel reposiciona a busca sem acumular observadores e tem reserva para navegador sem ResizeObserver');
ok(!src.includes('box-shadow:0 -48px 0 var(--bg-darker,#111114)') && src.includes('background:#111114;overflow:visible') && src.includes('box-shadow:0 -2px 0 #111114,0 2px 0 #111114') && src.includes("clone.style.boxShadow = 'none'"), 'a faixa sticky preserva abas primárias inteiras, sela suas emendas e o portal não projeta tarja sobre busca, título ou conteúdo anterior');
ok(src.includes('var tabsHost = searchWrap && searchWrap.parentNode') && src.includes('tabsHost.insertBefore(root, searchWrap.nextSibling)'), 'no celular as abas ficam imediatamente após a busca, sem cards atravessando a faixa fixa');
ok(src.includes('top:calc(var(--topbar-h,60px) + var(--hamburger-dd-h,0px) + var(--backheader-h,0px) + var(--stickybar-h,0px) - 1px);z-index:31') && !src.includes('position:sticky;top:var(--scroll-anchor,120px);z-index:30;isolation:isolate;box-shadow:0 8px 12px -12px'), 'abas encostam na busca sticky; o respiro de scroll não vira vão visível');
ok(src.includes('const allRoundsColumns = gRounds.map') && src.includes('class="bracket-round-column" data-round-num="${ri + 1}"') && src.includes('data-hscroll="groups:${_hsKey(sg.name || gi)}"'), 'rodadas de grupos ficam em colunas sucessivas no mesmo trilho horizontal');
ok(src.includes('min-width:280px;max-width:360px;align-self:flex-start') && src.includes('bracket-columns-track" style="display:flex;align-items:flex-start;gap:24px'), 'cada cabeçalho de rodada é limitado à própria coluna, sem máscara atravessar a chave');
ok(src.includes('function _limparCamadasTransitóriasDaChave') && src.includes('regression_score_save_does_not_duplicate_bracket_chrome') && src.includes('container._bracketPaintEpoch') && src.includes('aindaEhAPinturaAtual'), 'salvar placar invalida pinturas antigas e desmonta abas/portais antes do novo render');
ok(src.includes('function _bracketGeneralView') && src.includes('data-bracket-general-view') && src.includes('data-bracket-subtab="__general"') && src.includes('data-bracket-subtab="__upcoming"') && src.includes('data-bracket-upcoming') && src.includes('data-bracket-scheduled-at') && src.includes('generalAgendaByGender[gender]') && src.includes('regression_general_agenda_moves_visible_cards') && src.includes('regression_general_view_must_not_hide_itself') && src.includes('regression_general_round_columns') && src.includes('hasResult') && src.includes('entries.sort'), 'eventos concentrados têm Geral e Próximos como agenda operacional sem placar, ordenada por horário e quadra');
ok(src.includes('regression_operational_view_stays_after_tournament_details') && src.includes("scope.querySelector('#tourn-grid-container')") && src.includes("operationalAnchor.insertAdjacentElement('afterend', view)"), 'Geral e Próximos jogos ficam abaixo do card de detalhes e antes das rodadas');
ok(src.includes('regression_general_round_headings_stick_after_cards_move') && src.includes("window.addEventListener('scroll', window._bracketRoundHeadingResizeListener") && src.includes('regression_primary_gender_tabs_are_never_vertically_clipped'), 'a visão Geral sincroniza cabeçalhos após mover cards e as abas de gênero não são recortadas verticalmente');
ok(src.includes('function _matchCardResultTimestamp') && src.includes('var _playedMs = _isConcentratedEvent ? _matchCardResultTimestamp(m) : null') && src.includes("_playedMs ? 'var(--sp-c-4ade80,#4ade80)' : 'var(--sp-c-7dd3fc,#7dd3fc)'") && src.includes('No evento concentrado a categoria é o contexto do jogo'), 'card concentrado mantém categoria após placar e troca previsão azul por horário jogado verde no mesmo slot');
ok(src.includes('data-bracket-result-at') && src.includes('window._markBracketJustScored = function') && src.includes('var justScoredByTournament = window._bracketJustScoredByTournament') && src.includes('var isJustScored = onlyReady'), 'Próximos jogos só conserva o último placar recém-lançado na sessão atual');
ok(src.includes('scoreplace_bracket_tab_state_') && src.includes('regression_operational_tab_survives_dashboard_round_trip') && src.includes('regression_operational_cards_have_equal_height'), 'a visão operacional sobrevive ao retorno do dashboard e nivela os cards reais');
ok(src.includes('defaultAgendaGender') && src.includes("'__general'") && src.includes('regression_operational_tabs_open_on_next_game') && src.includes('regression_operational_tabs_always_focus_next_game') && src.includes('regression_operational_tabs_scroll_to_next_scheduled_game') && src.includes('data-bracket-result-at') && src.includes('scrollRoot.scrollTop = targetTop') && src.includes('track.scrollLeft = targetLeft') && src.includes('setTimeout(focusOperationalNextGame, 80)'), 'Geral é a aba inicial da agenda e Geral/Próximos levam deterministicamente o próximo jogo sem placar ao topo útil');
ok(src.includes('regression_operational_focus_reserves_round_heading') && src.includes("closest('.bracket-general-round-column, .bracket-round-column')") && src.includes('var portalReserve = headingHeight ? headingHeight + 30 : 68;') && src.includes('var safeTop = rootRect.bottom + Math.max(12, portalReserve);'), 'o foco operacional reserva a altura da régua de Rodada antes de rolar, mantendo o card inteiro abaixo do cabeçalho fixo');
ok(src.includes('root._bracketFocusToken') && !src.includes('view._bracketFocusToken'), 'o cancelamento do foco operacional usa o contêiner recebido no escopo, sem referência livre em runtime');

console.log('\n' + (fail ? '❌' : '✅') + ' chaves-abas-estáveis: ' + pass + ' asserts ok, ' + fail + ' falharam');
process.exitCode = fail ? 1 : 0;
