'use strict';
const H = require('./render-harness'); const W = H.sandbox;
require('./headless').load('participants.js');
let failed = 0; const ok = (v, m) => { if (v) console.log('✓ ' + m); else { failed++; console.error('✗ ' + m); } };
const t = { id: 'T', participants: [{ uid: 'uR1', displayName: 'Rodrigo' }, { uid: 'uR2', displayName: 'Rodrigo' }], checkedIn: {}, absent: {} };
const calls = []; W.AppStore.tournaments = [t]; W.AppStore.mutate = () => { throw new Error('sem mutação local'); };
W.FirestoreDB = { setTournamentPresence(...args) { calls.push(args); return Promise.resolve({ ok: true }); } };
W._presenceBusyUntil = W._reRenderParticipantsStable = () => {};
W._applyCheckInToggle('T', 'Rodrigo', 'uR2');
ok(calls.length === 1 && calls[0][1] === 'uR2', 'UID do segundo homônimo chega intacto à Function');
ok(Object.keys(t.checkedIn).length === 0, 'o nome homônimo não é usado para gravar localmente');
console.log((failed ? '❌' : '✅') + ' checkin-toggle-uid'); process.exit(failed ? 1 : 0);
