'use strict';
const fs = require('fs'); let fail = 0;
const ok = (value, message) => { console.log((value ? '✓ ' : '✗ ') + message); if (!value) fail++; };
const source = fs.readFileSync('functions/index.js', 'utf8');
const start = source.indexOf('exports.requestCanonicalRegistration = onCall');
const end = source.indexOf('\nexports.', start + 8);
const body = source.slice(start, end < 0 ? source.length : end);
ok(start >= 0 && body.includes('db.runTransaction') && body.includes('request.auth && request.auth.uid'), 'registro canônico decide em Function transacional pelo UID autenticado');
ok(body.includes('_canonicalRegistrationCanStart') && body.includes('failed-precondition'), 'registro canônico não mistura torneio legado ou já sorteado');
ok(body.includes('_enrollCore.enrollmentOpen(tournament, Date.now())') && body.includes('registration_deadline_passed'), 'registro canônico respeita prazo e encerramento antes do create');
ok(body.includes('_categoryEligibility.decideEnrollment') && body.includes('tx.get(profileRef)'), 'perfil e rigor são decididos no servidor');
ok(body.includes('_amizadeLock.exigirAtivos(tx, db, [callerUid]'), 'inscrição lê o lifecycle dentro da mesma transação antes de criar');
ok(body.includes('existingCategoryIds: existing') && body.includes('registration.participantKey === "uid:" + callerUid'), 'idempotência e exclusividade usam UID e categoria estáveis');
ok(body.includes('.where("participantKey", "==", "uid:" + callerUid)') && !body.includes('tx.get(tournamentRef.collection("registrations"))'), 'inscrição consulta somente os registros do próprio UID, sem varrer o elenco');
ok(body.includes('_registrationMutations.enroll(') && body.includes('{ uid: callerUid }'), 'registro novo recebe participantKey estrutural pelo núcleo, nunca nome');
ok(body.includes('_registrationMutations.enroll(') && body.includes('enrollment.creates.forEach'), 'callable nova usa o núcleo canônico único para decidir creates');
ok(body.includes('tx.create(tournamentRef.collection("registrations")') && !body.includes('participants:'), 'Function grava só o registro canônico, sem dual-write no roster');
const deenrollStart = source.indexOf('exports.deenrollParticipant = onCall');
const deenrollEnd = source.indexOf('\nexports.', deenrollStart + 8);
const deenroll = source.slice(deenrollStart, deenrollEnd < 0 ? source.length : deenrollEnd);
ok(deenroll.includes('_loadCanonicalRosterForMutation') && deenroll.includes('_registrationMutations.withdraw(') && deenroll.includes('if (!out.canonical)'), 'desinscrição materializada usa o núcleo canônico e não replica escrita legada');
const standbyStart = source.indexOf('exports.leaveStandby = onCall');
const standbyEnd = source.indexOf('\nexports.', standbyStart + 8);
const standby = source.slice(standbyStart, standbyEnd < 0 ? source.length : standbyEnd);
ok(standby.includes('_loadCanonicalRosterForMutation') && standby.includes('_registrationMutations.leaveWaitlist(') && standby.includes('if (!out.canonical)'), 'saída da espera materializada usa o núcleo canônico e não replica escrita legada');
const formStart = source.indexOf('exports.formPair = onCall');
const formEnd = source.indexOf('\nexports.', formStart + 8);
const form = source.slice(formStart, formEnd < 0 ? source.length : formEnd);
ok(form.includes('_registrationMutations.pairParticipants(') && form.includes('categoryId é obrigatório') && form.includes('nome não é identidade') && form.includes('if (!out.canonical)'), 'formação canônica exige categoria e identidade estável, sem replicação legada');
const splitStart = source.indexOf('exports.splitPair = onCall');
const splitEnd = source.indexOf('\nexports.', splitStart + 8);
const split = source.slice(splitStart, splitEnd < 0 ? source.length : splitEnd);
ok(split.includes('_registrationMutations.splitParticipants(') && split.includes('categoryId é obrigatório') && split.includes('nome não é identidade') && split.includes('if (!out.canonical)'), 'desfazimento canônico exige categoria e identidade estável, sem replicação legada');
const deletionStart = source.indexOf('exports.deleteAccount = onCall');
const deletionEnd = source.indexOf('\nexports.', deletionStart + 8);
const deletion = source.slice(deletionStart, deletionEnd < 0 ? source.length : deletionEnd);
ok(deletion.includes('_anonymizeCanonicalRegistrations(db, uid)') && deletion.includes('canonicalRegistrationsAnonymized'), 'exclusão delega a anonimização do registro canônico à Function');
process.exit(fail ? 1 : 0);
