'use strict';
const fs = require('fs');
let failed = 0;
function ok(condition, message) { if (condition) console.log('✓ ' + message); else { console.error('✗ ' + message); failed++; } }
const ui = fs.readFileSync('js/views/tournaments.js', 'utf8');
const a = ui.indexOf('window.removeParticipantFunction');
const b = ui.indexOf('window._applySplitParticipantFresh', a);
const block = ui.slice(a, b);
ok(/_callFn\('removeTournamentParticipant'/.test(block) && !/(?:commitTournamentTx|AppStore\.mutate|_sendUserNotification)/.test(block), 'remoção administrativa só despacha a CF');
const fn = fs.readFileSync('functions-autodraw/index.js', 'utf8');
const x = fn.indexOf('exports.removeTournamentParticipant');
const y = fn.indexOf('// ─── Reset para inscrições', x);
const server = fn.slice(x, y);
ok(/_isTournamentAdmin/.test(server) && /runTransaction/.test(server) && /notificationOutbox/.test(server), 'CF remove com autorização, transação e outbox');
const s = ui.indexOf('window.splitParticipantFunction');
const e = ui.indexOf('// Self-healing:', s);
const split = ui.slice(s, e);
ok(/_callFn\('splitTournamentParticipant'/.test(split) && !/commitTournamentTx/.test(split), 'desmembramento de dupla só despacha a CF');
const sx = fn.indexOf('exports.splitTournamentParticipant');
const sy = fn.indexOf('// ─── Reset para inscrições', sx);
ok(/_isTournamentAdmin/.test(fn.slice(sx, sy)) && /_gravaTorneio/.test(fn.slice(sx, sy)), 'CF desmembra a dupla no documento fresco');
const p = ui.indexOf('window._autoPresenceFromVenue');
const pe = ui.indexOf('// Mede a altura', p);
const presence = ui.slice(p, pe);
ok(/setTournamentPresence\(t\.id, cu\.uid, 'present'\)/.test(presence) && !/AppStore\.mutate/.test(presence), 'presença automática usa a CF estreita');
const c = ui.indexOf('window._cancelPairRequest = function');
const ce = ui.indexOf('// v2.8.90:', c);
const cancel = ui.slice(c, ce);
ok(/_callFn\('cancelTournamentPairRequest'/.test(cancel) && !/(?:commitTournamentTx|_sendUserNotification)/.test(cancel), 'cancelamento de convite só despacha a CF');
const cx = fn.indexOf('exports.cancelTournamentPairRequest');
const cy = fn.indexOf('// ─── Placeholders', cx);
ok(/_isTournamentAdmin/.test(fn.slice(cx, cy)) && /notificationOutbox/.test(fn.slice(cx, cy)), 'CF autoriza e notifica o cancelamento');
const d = ui.indexOf('var _afterPresence');
const de = ui.indexOf('if (!window.inviteModalSetupDone)', d);
const drawClose = ui.slice(d, de);
ok(/_setTournamentEnrollmentStatus\(tId, 'close', \{ forDraw: true \}\)/.test(drawClose) && !/commitTournamentTx/.test(drawClose), 'fechamento antes do sorteio só despacha a CF');
const ex = fn.indexOf('exports.setTournamentEnrollmentStatus');
const ey = fn.indexOf('exports.runEnrollmentSlotsDraw', ex);
ok(/forDraw/.test(fn.slice(ex, ey)) && /_reopenIfDrawCancelled/.test(fn.slice(ex, ey)), 'CF conserva a reabertura do sorteio cancelado');
const renderChecks = ui.indexOf('var _checksKey = tournamentId');
const organizers = ui.indexOf('// Build organizers section', renderChecks);
const reconciliation = ui.slice(renderChecks, organizers);
ok(/_callFn\('deduplicateTournamentParticipants'/.test(reconciliation) && /_callFn\('drainTournamentWaitlists'/.test(reconciliation) && !/(?:commitTournamentTx|AppStore\.mutate)/.test(reconciliation), 'higiene de elenco na dashboard só despacha Functions');
const dx = fn.indexOf('exports.deduplicateTournamentParticipants');
const dy = fn.indexOf('// ─── Reset para inscrições', dx);
const hygiene = fn.slice(dx, dy);
ok(/_isTournamentAdmin/.test(hygiene) && /runTransaction/.test(hygiene) && /_deduplicateParticipants/.test(hygiene) && /_drainWaitlistsIfOpen/.test(hygiene), 'Functions reconciliam elenco fresco com autorização e transação');
const startDraw = ui.indexOf('var movedCount =');
const endDraw = ui.indexOf('// v2.1.20:', startDraw);
ok(!/AppStore\.mutate|_autoMoveAbsentToStandby\(t\)|_autoMoveSoloToWaitlist\(t\)/.test(ui.slice(startDraw, endDraw)), 'pré-sorteio não muta ausentes nem sem-dupla no navegador');
process.exitCode = failed ? 1 : 0;
