'use strict';
const fs=require('fs');
const i=fs.readFileSync('functions-autodraw/index.js','utf8');
const b=fs.readFileSync('js/views/bracket-logic.js','utf8');
const d=fs.readFileSync('js/views/tournaments-draw.js','utf8');
let f=0;
const ok=(v,s)=>{console.log((v?'✓ ':'✗ ')+s);if(!v)f++;};
const a=i.slice(i.indexOf('exports.resolvePendingDraw'),i.indexOf('// ─── Reconciliação',i.indexOf('exports.resolvePendingDraw')));
const c=b.slice(b.indexOf('window._publishPendingDraw'),b.indexOf('// v2.7.6:',b.indexOf('window._publishPendingDraw')));
const draw=i.slice(i.indexOf('exports.drawRound'),i.indexOf('// ─── Convite de dupla',i.indexOf('exports.drawRound')));
const agenda=i.slice(i.indexOf('exports.setPendingInitialSchedule'),i.indexOf('// ─── DECISÃO DO ORGANIZADOR',i.indexOf('exports.setPendingInitialSchedule')));
ok(a.includes('db.runTransaction')&&a.includes('_leTorneio(tx,ref,tId)')&&a.includes('_gravaTorneio(tx,ref,t,antes'),'Function relê e grava pendingDraw na transação');
ok(a.includes('_isTournamentAdmin(t,uid)'),'Function exige organização por uid');
ok(a.includes("action==='annul'")&&a.includes('t.pendingDraw=null')&&a.includes("if (action === 'publish') throw new HttpsError('failed-precondition','O rascunho privado não foi encontrado.')")&&!a.includes('t.lastAutoDrawAt=null'),'Anular limpa marcador/cofre sem apagar estado anterior; publicar continua exigindo cofre íntegro');
ok(c.includes("_callCF('resolvePendingDraw'")&&!/AppStore\.mutate|_notifyDrawPersonalized/.test(c),'cliente só despacha a Function');
ok(c.includes("Sorteio não anulado")&&c.includes("Sorteio já anulado"),'falha ou ausência do rascunho recebe retorno visual, nunca silêncio');
ok(c.includes('_teamDrawReviewApproved')&&c.includes('delete window._teamDrawReviewApproved[String(tId)]'),'Anular também apaga a aprovação local para exigir nova decisão no próximo sorteio');
ok(draw.includes("kind: 'initial'")&&draw.includes('draft: _rascunhoDoSorteioInicial(t)')&&draw.includes('_refRascunhoInicialPrivado(ref)')&&draw.includes('_stageInitial'),'Sorteio inicial vai ao cofre privado antes de materializar a chave');
ok(a.includes("pd.kind === 'initial'")&&a.includes('_aplicaRascunhoDoSorteioInicial(t, pd.draft)'),'Publicação aplica somente o rascunho derivado na transação');
ok(/if \(d\.staged\) \{[\s\S]*?\} else \{[\s\S]*?_notifyDrawPersonalized/.test(d),'Rascunho não dispara notificação antes da publicação');
ok(agenda.includes('db.runTransaction')&&agenda.includes('_isTournamentAdmin(t, uid)')&&agenda.includes('pd.kind !== \'initial\''),'Agenda do rascunho é transacional e exclusiva da organização');
ok(agenda.includes('pd.draft.matches')&&agenda.includes('match.court = item.court')&&agenda.includes('match.scheduleLocked = item.scheduleLocked'),'Agenda altera somente jogos do rascunho e fixa apenas escolhas manuais antes da publicação');
ok(b.includes('window._openPendingInitialSchedule')&&b.includes("_callCF('setPendingInitialSchedule'"),'Cliente planeja no rascunho e delega o salvamento à Function');
ok(i.includes('exports.getPendingInitialDraw')&&i.includes('_isTournamentAdmin(t, uid)')&&i.includes("collection('privateDraws')"),'Prévia privada só é lida pela Function após conferir a organização');
ok(draw.includes('_requireExplicitTeamDrawPlan(t, tId)')&&i.includes('modeConfirmed')&&i.includes('categorySchedule')&&i.includes('plan.confirmed === true'),'Function bloqueia competição por times sem modo e agenda explicitamente escolhidos');
ok(d.includes('name="team-draw-mode"')&&d.includes('modeConfirmed:true')&&d.includes('confirmed:true'),'Tela exige e persiste modo e agenda escolhidos pela organização');
ok(d.includes('data-team-court-rank')&&d.includes('courtOrder:selectedCourtOrder'),'Tela permite declarar a prioridade das quadras antes do sorteio');
ok(agenda.includes('match.matchNumber = matchNumber.get(item.matchId)')&&agenda.includes('courtRank'),'Agenda do rascunho renumera jogos continuamente pela ordem de horário e quadra');
process.exit(f?1:0);
