'use strict';
const fs=require('fs');
const i=fs.readFileSync('functions-autodraw/index.js','utf8');
const b=fs.readFileSync('js/views/bracket-logic.js','utf8');
const d=fs.readFileSync('js/views/tournaments-draw.js','utf8');
let f=0;
const ok=(v,s)=>{console.log((v?'✓ ':'✗ ')+s);if(!v)f++;};
const a=i.slice(i.indexOf('exports.resolvePendingDraw'),i.indexOf('// ─── Reconciliação',i.indexOf('exports.resolvePendingDraw')));
const c=b.slice(b.indexOf('window._publishPendingDraw'),b.indexOf('// v2.7.6:',b.indexOf('window._publishPendingDraw')));
const draw=i.slice(i.indexOf('exports.drawRound'),i.indexOf('// ─── Convite de dupla',i.indexOf('exports.drawRound')));
ok(a.includes('db.runTransaction')&&a.includes('_leTorneio(tx,ref,tId)')&&a.includes('_gravaTorneio(tx,ref,t,antes'),'Function relê e grava pendingDraw na transação');
ok(a.includes('_isTournamentAdmin(t,uid)'),'Function exige organização por uid');
ok(a.includes("action==='annul'")&&a.includes('t.pendingDraw=null'),'Function resolve publicar e anular');
ok(c.includes("_callCF('resolvePendingDraw'")&&!/AppStore\.mutate|_notifyDrawPersonalized/.test(c),'cliente só despacha a Function');
ok(draw.includes("kind: 'initial'")&&draw.includes('draft: _rascunhoDoSorteioInicial(t)')&&draw.includes('_stageInitial'),'Sorteio inicial de times fica em rascunho antes de materializar a chave');
ok(a.includes("pd.kind === 'initial'")&&a.includes('_aplicaRascunhoDoSorteioInicial(t, pd.draft)'),'Publicação aplica somente o rascunho derivado na transação');
ok(/if \(d\.staged\) \{[\s\S]*?\} else \{[\s\S]*?_notifyDrawPersonalized/.test(d),'Rascunho não dispara notificação antes da publicação');
process.exit(f?1:0);
