'use strict';
const fs=require('fs');
let f=0;const ok=(v,s)=>{console.log((v?'✓ ':'✗ ')+s);if(!v)f++;};
const db=fs.readFileSync('js/firebase-db.js','utf8');
const enroll=db.slice(db.indexOf('async enrollParticipant'),db.indexOf('// v1.8.40: SAIR',db.indexOf('async enrollParticipant')));
const deenroll=db.slice(db.indexOf('async deenrollParticipant'),db.indexOf('// Formar/desfazer',db.indexOf('async deenrollParticipant')));
ok(enroll.includes("this._callFn('enrollParticipant'")&&!enroll.includes('_enrollParticipantTx('),'inscrição não volta a escrever pelo cliente');
ok(deenroll.includes("this._callFn('deenrollParticipant'")&&!deenroll.includes('_deenrollParticipantTx('),'desinscrição não volta a escrever pelo cliente');
const e=fs.readFileSync('js/views/tournaments-enrollment.js','utf8');
const add=e.slice(e.indexOf('window._doAddParticipant'),e.indexOf('window.addTeamFunction'));
ok(add.includes("_callCF('reconcileMonarchEnrollment'")&&!add.includes('saveTournament(t)'),'Rei/Rainha despacha intenção sem salvar o torneio no navegador');
const fn=fs.readFileSync('functions-autodraw/index.js','utf8');
const monarch=fn.slice(fn.indexOf('exports.reconcileMonarchEnrollment'),fn.indexOf('// ─── Publicação',fn.indexOf('exports.reconcileMonarchEnrollment')));
ok(monarch.includes('db.runTransaction')&&monarch.includes('_onParticipantAddedToMonarchRound')&&monarch.includes('_isTournamentAdmin'),'servidor decide espera e grupo Rei/Rainha em transação autorizada');
process.exit(f?1:0);
