const { onSchedule } = require('firebase-functions/v2/scheduler');
const { onDocumentCreated } = require('firebase-functions/v2/firestore');
const { initializeApp } = require('firebase-admin/app');
const { getFirestore } = require('firebase-admin/firestore');
const { getMessaging } = require('firebase-admin/messaging');

initializeApp();
const db = getFirestore();

// ─── Auto-Draw: runs every hour, checks for pending draws ───────────────────
exports.autoDraw = onSchedule('every 1 hours', async (event) => {
  const now = new Date();
  const snap = await db.collection('tournaments').get();

  for (const doc of snap.docs) {
    const t = doc.data();
    const tId = doc.id;

    // Skip if not Liga/Ranking format with auto-draw
    const isLiga = t.format === 'Liga' || t.format === 'Ranking';
    if (!isLiga) continue;
    if (t.drawManual) continue;
    if (!t.drawFirstDate) continue;
    if (t.status === 'finished') continue;

    // Check participants
    const participants = Array.isArray(t.participants) ? t.participants : [];
    if (participants.length < 2) continue;

    // Calculate next draw date.
    // FIX timezone: o horário agendado (drawFirstDate + drawFirstTime) é hora
    // LOCAL do Brasil (BRT, UTC-3, sem horário de verão desde 2019). O servidor
    // roda em UTC — sem o offset, "19:00" virava 19:00 UTC = 16:00 BRT e o
    // sorteio disparava ~3h ANTES do horário programado. Anexar "-03:00"
    // interpreta corretamente como BRT.
    let _fdDate = String(t.drawFirstDate);
    let _fdTime = t.drawFirstTime || '19:00';
    if (_fdDate.indexOf('T') !== -1) {
      const _parts = _fdDate.split('T');
      _fdDate = _parts[0];
      if (_parts[1]) _fdTime = _parts[1].slice(0, 5); // HH:MM
    }
    const firstDrawStr = _fdDate + 'T' + _fdTime + ':00-03:00';
    const firstDraw = new Date(firstDrawStr);
    if (isNaN(firstDraw.getTime())) continue;

    const intervalMs = (t.drawIntervalDays || 7) * 86400000;

    // If first draw is in the future, skip
    if (firstDraw > now) continue;

    // Calculate how many intervals have passed
    const elapsed = now.getTime() - firstDraw.getTime();
    const intervalsCompleted = Math.floor(elapsed / intervalMs);
    const expectedRounds = intervalsCompleted + 1;

    const currentRounds = Array.isArray(t.rounds) ? t.rounds.length : 0;
    const currentRodadas = Array.isArray(t.rodadas) ? t.rodadas.length : 0;
    const actualRounds = Math.max(currentRounds, currentRodadas);

    // If we need more rounds, generate one
    if (actualRounds < expectedRounds) {
      console.log(`Auto-draw: generating round ${actualRounds + 1} for ${tId} (${t.name})`);

      try {
        // Get active participants
        let activePlayers = participants.map(p => {
          return typeof p === 'string' ? { displayName: p, name: p } : p;
        }).filter(p => {
          const name = p.displayName || p.name || p.email || '';
          return name && name !== 'BYE';
        });

        // Filter by inactivity
        if (t.ligaInactivityWeeks && t.ligaInactivityWeeks > 0) {
          const inactivityMs = t.ligaInactivityWeeks * 7 * 86400000;
          activePlayers = activePlayers.filter(p => {
            if (!p.lastActive) return true;
            return (now.getTime() - new Date(p.lastActive).getTime()) < inactivityMs;
          });
        }

        if (activePlayers.length < 2) continue;

        // Generate pairings (shuffle + pair)
        const names = activePlayers.map(p => p.displayName || p.name || p.email);
        const shuffled = [...names].sort(() => Math.random() - 0.5);
        const matches = [];

        for (let i = 0; i < shuffled.length; i += 2) {
          if (i + 1 < shuffled.length) {
            matches.push({
              p1: shuffled[i],
              p2: shuffled[i + 1],
              scoreP1: null,
              scoreP2: null,
              winner: null
            });
          }
        }

        const newRound = {
          roundNumber: actualRounds + 1,
          matches: matches,
          createdAt: now.toISOString(),
          autoGenerated: true
        };

        const rounds = Array.isArray(t.rounds) ? [...t.rounds] : [];
        rounds.push(newRound);

        await db.collection('tournaments').doc(tId).update({
          rounds: rounds,
          updatedAt: now.toISOString(),
          lastAutoDrawAt: now.toISOString()
        });

        console.log(`Auto-draw: round ${newRound.roundNumber} created with ${matches.length} matches`);

        // Notify participants
        for (const p of activePlayers) {
          const email = p.email;
          if (!email) continue;
          try {
            const userSnap = await db.collection('users').where('email', '==', email).limit(1).get();
            if (!userSnap.empty) {
              const uid = userSnap.docs[0].id;
              const profile = userSnap.docs[0].data();
              if (profile.notifyPlatform !== false) {
                await db.collection('users').doc(uid).collection('notifications').add({
                  type: 'draw',
                  fromUid: 'system',
                  fromName: 'scoreplace.app',
                  fromPhoto: '',
                  tournamentId: tId,
                  tournamentName: t.name || '',
                  message: 'Nova rodada sorteada automaticamente! Confira seus jogos.',
                  createdAt: now.toISOString(),
                  read: false
                });
              }
            }
          } catch (e) {
            console.warn(`Notification error for ${email}:`, e.message);
          }
        }
      } catch (err) {
        console.error(`Auto-draw error for ${tId}:`, err);
      }
    }
  }
});

// ─── Push Notifications via FCM ─────────────────────────────────────────────
exports.sendPushNotification = onDocumentCreated('users/{userId}/notifications/{notifId}', async (event) => {
  const snap = event.data;
  if (!snap) return;

  const userId = event.params.userId;
  const notifData = snap.data();

  const userDoc = await db.collection('users').doc(userId).get();
  if (!userDoc.exists) return;

  const userData = userDoc.data();
  const fcmToken = userData.fcmToken;
  if (!fcmToken) return;

  const message = {
    token: fcmToken,
    notification: {
      title: notifData.tournamentName || 'scoreplace.app',
      body: notifData.message || 'Você tem uma nova notificação.'
    },
    webpush: {
      fcmOptions: {
        link: notifData.tournamentId
          ? `https://scoreplace.app/#tournaments/${notifData.tournamentId}`
          : 'https://scoreplace.app/#notifications'
      },
      notification: {
        icon: 'https://scoreplace.app/icons/icon-192.svg',
        badge: 'https://scoreplace.app/icons/icon-192.svg'
      }
    }
  };

  try {
    await getMessaging().send(message);
    console.log(`Push sent to ${userId}`);
  } catch (err) {
    console.warn(`Push failed for ${userId}:`, err.message);
    if (err.code === 'messaging/invalid-registration-token' ||
        err.code === 'messaging/registration-token-not-registered') {
      await db.collection('users').doc(userId).update({ fcmToken: require('firebase-admin/firestore').FieldValue.delete() });
    }
  }
});
